/**
 * Scenario 66: They Told Us First.
 *
 * A stranger emails the security mailbox to say your members' data is on a
 * forum, and attaches twenty records to prove it.
 *
 * WHAT THIS TEACHES
 *
 * How to receive bad news from outside, which is a skill with two failure modes
 * and most floors have both.
 *
 * The first is dismissal. Unsolicited mail about a breach looks exactly like
 * the scam that arrives every week, and the reflex is to bin it. The second is
 * panic: treating an unverified claim as established fact, telling the
 * executive there has been a breach, and finding out at four o'clock that
 * somebody sent a mail merge to two hundred companies.
 *
 * Neither is necessary, because the claim is testable and the test is quick.
 * Twenty records either match real members or they do not, and the fields they
 * contain either exist together in one system or they do not. Ninety seconds of
 * checking settles what an hour of arguing will not.
 *
 * WHAT THE DIFFERENCE ACTUALLY IS
 *
 * A second message arrives the same morning saying much the same thing, and it
 * is a scam. The discriminator is not tone, spelling or politeness, and a floor
 * that grades on those will get it wrong in both directions. It is whether the
 * sender proves the claim before asking for anything. One attached data. The
 * other attached an invoice.
 */

import type { Scenario, ScenarioTruth } from '@soc/shared';

import { COMMON_ACTIONS } from './actions.js';
import {
  ALSO_WORKS,
  COUNT_ONLY,
  CORRECT_STEP,
  DUMP_ALL,
  MUTATE,
  STATUS_CHECK,
  TOUCH_ATTACKER,
  WRONG_TARGET,
} from './distractors.js';

const ID = 'they-told-us-first';

export const THEY_TOLD_US_FIRST: Scenario = {
  id: ID,
  title: 'They Told Us First',
  difficulty: 'beginner',
  durationMinutes: 45,
  situation:
    'It is 09:30 at Fenmarch Credit Union. Somebody nobody has heard of emailed the security ' +
    'mailbox to say member records are on a public forum, and attached twenty of them.',
  roles: [
    'soc-operator',
    'log-analyst',
    'network-analyst',
    'forensics',
    'cloud-security',
    'mitigation-specialist',
    'ir-lead',
  ],
  actions: COMMON_ACTIONS,

  events: [
    {
      id: 'ev.1',
      atSeconds: 0,
      surface: 'alert-queue',
      summary: 'An unsolicited email says member data is on a forum',
      detail:
        'A message to security@fenmarch.example from an address at a university domain states that ' +
        'a file of Fenmarch member records was posted to a public forum on 19 August. It attaches ' +
        'twenty records as evidence, names the forum and the thread, asks for an address to send ' +
        'the full findings to, and asks nothing else. No payment is mentioned. Rule history: the ' +
        'security mailbox receives four or five claims like this a month.',
      source: 'security mailbox',
      claimedSeverity: 'medium',
    },
    {
      id: 'ev.2',
      atSeconds: 140,
      surface: 'raw-log',
      summary: 'All twenty records match real members',
      detail:
        'All twenty membership numbers exist. All twenty names, dates of birth and postcodes match ' +
        'the member record exactly. Three of the fields present are the loan-to-value ratio, the ' +
        'broker reference and the affordability band, which are not held on the member record at ' +
        'all and exist only in the mortgage reporting system. No member in the sample has been ' +
        'notified of anything.',
      source: 'member system',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.3',
      atSeconds: 300,
      surface: 'cloud-audit',
      summary: 'The field set matches one report exactly',
      detail:
        'The combination of member number, name, date of birth, postcode, loan-to-value ratio, ' +
        'broker reference and affordability band appears together in exactly one place: the ' +
        'monthly Broker Introduced Lending report generated by the mortgage reporting tool. The ' +
        'column order in the sample matches the report\'s column order. The report covers every ' +
        'mortgage application introduced by a broker, and the August file holds 9,412 rows.',
      source: 'mortgage reporting',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.4',
      atSeconds: 460,
      surface: 'cloud-audit',
      summary: 'The share those reports are written to was made public in January',
      detail:
        'The reports are written to a cloud storage container each month. Change CHG-9902, applied ' +
        'on 14 January and described as "open read for broker portal integration testing", set the ' +
        'container access policy to public read. The integration testing finished on 22 January. ' +
        'The change was never reversed. Eight monthly reports have been written to the container ' +
        'since, the oldest in February.',
      source: 'cloud storage',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.5',
      atSeconds: 620,
      surface: 'network-flow',
      summary: 'Four hundred downloads from sixty addresses since February',
      detail:
        'The container access log records 412 successful downloads of report files from 61 distinct ' +
        'addresses between 3 February and this morning. Nine of the addresses belong to the broker ' +
        'portal integration and account for 38 downloads. The remaining 52 addresses are ' +
        'unrecognised. The first unrecognised download was on 11 February, eighteen days after the ' +
        'container was opened.',
      source: 'cloud storage',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.9',
      atSeconds: 700,
      surface: 'host-artefact',
      summary: 'The posted file is the whole August report',
      detail:
        'A copy of the forum attachment, retrieved and hashed, is 9,412 rows and matches the ' +
        'August Broker Introduced Lending report exactly, including the header row and the trailing ' +
        'newline. The account number column is present and unredacted. File metadata carries a ' +
        'creation timestamp of 01:04 on 1 August, four minutes after the report job runs. Nothing ' +
        'in the file has been edited.',
      source: 'forum attachment',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.6',
      atSeconds: 780,
      surface: 'alert-queue',
      summary: 'The sender has asked for nothing',
      detail:
        'The sender writes from a university address, signs with a name and a departmental page ' +
        'that both resolve, references two previous disclosures to other organisations that are ' +
        'publicly documented, and offers to send full findings. There is no payment request, no ' +
        'deadline, no threat of publication, and no link to click. The attached sample is redacted ' +
        'in the account number field.',
      source: 'security mailbox',
      claimedSeverity: 'low',
    },
    {
      id: 'ev.7',
      atSeconds: 940,
      surface: 'alert-queue',
      summary: 'The broker portal reads that container every night',
      detail:
        'The broker portal integration pulls the monthly report from the container at 01:00 and ' +
        'loads it into the broker dashboard, which 340 mortgage brokers use to track their own ' +
        'introduced cases. Closing public read stops that job unless the integration is given a ' +
        'credential, which it has never had. Month end reporting runs on Thursday. The regulator ' +
        'must be told of a personal data breach within 72 hours of becoming aware.',
      source: 'lending operations',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.8',
      atSeconds: 1100,
      surface: 'alert-queue',
      summary: 'A second message arrives saying much the same thing',
      detail:
        'A message to the same mailbox at 10:14 states that Fenmarch has suffered a serious data ' +
        'breach, that the sender has obtained the database, and that a copy will be published in ' +
        '48 hours unless a fee is paid. It attaches nothing. It does not name a system, a record ' +
        'count, a date or a forum. The same wording appears in a published warning issued to the ' +
        'sector in June. The named payment address has received 41 transfers.',
      source: 'security mailbox',
      claimedSeverity: 'critical',
    },
  ],
};

export const THEY_TOLD_US_FIRST_TRUTH: ScenarioTruth = {
  scenarioId: ID,
  narrative: [
    'On 14 January a change set the cloud storage container holding the monthly Broker Introduced Lending report to public read, so that the broker portal integration could be tested. The testing finished on 22 January and the change was never reversed.',
    'Eight monthly reports have been written to that container since February. Each covers every mortgage application introduced by a broker, and the August file holds 9,412 rows.',
    'The container access log records 412 downloads from 61 addresses. Nine of those addresses are the broker portal and account for 38 downloads. The first unrecognised download was on 11 February, eighteen days after the container was opened.',
    'On 19 August a file of those records was posted to a public forum.',
    'A researcher found it, matched it to Fenmarch, and emailed the security mailbox with twenty records as evidence, a redacted account number field, a named forum and thread, and no request for anything.',
    'All twenty records match real members. Three of the fields in the sample exist nowhere except the mortgage reporting system, and the column order matches that report exactly, which is what identifies the source.',
    'A second message the same morning claims a breach, attaches nothing, names no system, record count, date or forum, and demands a fee within 48 hours. Its wording appears in a sector warning published in June.',
    'The real disclosure asked for nothing and proved its claim. The scam asked for money and proved nothing.',
  ],
  events: [
    {
      eventId: 'ev.1',
      verdict: 'malicious',
      stage: 'exfiltration',
      techniques: ['T1530'],
      firstResponder: 'soc-operator',
      alsoAppropriate: ['log-analyst', 'ir-lead'],
      correctActions: ['act.triage-high', 'act.investigate-hold'],
      outOfLaneActions: ['act.dismiss', 'act.declare', 'act.contact-attacker', 'act.attribute-named'],
      escalateTo: ['log-analyst', 'ir-lead'],
      why:
        'Four or five of these a month, and the reflex is to bin it. The reflex is wrong here for a ' +
        'reason visible without leaving the row: there are twenty records attached. A claim with ' +
        'evidence attached is a different object from a claim, because it can be checked, and ' +
        'checking it takes minutes. Resist the opposite reflex too. Nothing yet establishes that ' +
        'those records are real, so this is not the moment to declare an incident or tell anybody ' +
        'senior that there has been a breach: an hour from now that sentence is either true or a ' +
        'retraction, and retractions cost more than delay. Raise it, hold it open, and get ' +
        'somebody testing the sample. Do not reply to the sender yet, and above all do not follow ' +
        'anything in the message to the forum: that is a decision about engaging with an unknown ' +
        'party, and it belongs to the lead.',
      standIn:
        'Unsolicited mail claiming our member data is on a forum. We get four or five of these a ' +
        'month and I would normally bin it, except this one has twenty records attached. A claim ' +
        'with evidence can be checked in minutes. I am not declaring anything yet because nobody ' +
        'has confirmed those records are real, and I am not replying to the sender or going to ' +
        'that forum until the lead says so.',
      commandOptions: [
        { command: "awk -F, 'NR>1 {print $1}' /evidence/disclosure/sample.csv | head -20", correct: true, teaches: CORRECT_STEP },
        { command: 'head -3 /evidence/disclosure/sample.csv', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mailgw', ...STATUS_CHECK },
        { command: 'cat /var/log/mail/security-mailbox.log', ...DUMP_ALL },
        { command: 'curl -s http://203.0.113.90/thread/8812', ...TOUCH_ATTACKER },
      ],
      commandNudge:
        'Open the attached sample and see what fields it actually contains.',
      guidance:
        'Most of these are nonsense. Ask what makes this one checkable.',
    },
    {
      eventId: 'ev.2',
      verdict: 'malicious',
      stage: 'exfiltration',
      critical: true,
      techniques: ['T1530'],
      firstResponder: 'log-analyst',
      alsoAppropriate: ['forensics', 'ir-lead'],
      correctActions: ['act.timeline', 'act.corroborate'],
      outOfLaneActions: ['act.dismiss', 'act.attribute-named', 'act.contact-attacker', 'act.reset-password'],
      escalateTo: ['cloud-security', 'ir-lead'],
      why:
        'The claim is true, and it took one query. All twenty membership numbers exist and the ' +
        'names, dates of birth and postcodes match exactly. Anybody can make up a plausible list, ' +
        'and nobody can make up twenty membership numbers that all resolve. Then the part that ' +
        'does more work than the matching: three of the fields are the loan-to-value ratio, the ' +
        'broker reference and the affordability band, and none of those is on the member record. ' +
        'They exist somewhere else. So this is not simply real, it points at a specific system, ' +
        'and that is the whole difference between knowing something leaked and knowing where to ' +
        'go next. Say both parts out loud: the data is genuine, and the fields in it tell us which ' +
        'system to look at.',
      standIn:
        'It is real. All twenty membership numbers exist, and the names, dates of birth and ' +
        'postcodes match exactly. Nobody invents twenty membership numbers that all resolve. And ' +
        'three of the fields are not on the member record at all: loan-to-value, broker reference, ' +
        'affordability band. Those live somewhere else, which means the sample tells us where to ' +
        'look and not just that something leaked.',
      commandOptions: [
        { command: "awk -F, 'NR>1 {print $1}' /evidence/disclosure/sample.csv | while read m; do grep -c \"^$m,\" /var/data/members.csv; done | sort | uniq -c", correct: true, teaches: CORRECT_STEP },
        { command: 'head -1 /evidence/disclosure/sample.csv | tr , "\\n"', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status memberdb', ...STATUS_CHECK },
        { command: 'cat /var/data/members.csv', ...DUMP_ALL },
        { command: 'grep -c . /evidence/disclosure/sample.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'Check the sample against the member system, then look at which fields are in it.',
      guidance:
        'Anybody can invent names. Ask what in that file could not have been guessed.',
    },
    {
      eventId: 'ev.3',
      verdict: 'malicious',
      stage: 'collection',
      critical: true,
      techniques: ['T1530'],
      firstResponder: 'cloud-security',
      alsoAppropriate: ['log-analyst', 'ir-lead'],
      correctActions: ['act.iam-audit', 'act.corroborate'],
      outOfLaneActions: ['act.revoke-key', 'act.attribute-named', 'act.dismiss', 'act.reset-password'],
      escalateTo: ['ir-lead', 'network-analyst'],
      why:
        'Field sets identify sources, and this one identifies exactly one. Member number, name, ' +
        'date of birth, postcode, loan-to-value, broker reference and affordability band appear ' +
        'together in one place in this organisation: the monthly Broker Introduced Lending report. ' +
        'The column order matching the report as well removes any remaining doubt, because two ' +
        'systems holding the same fields would not order them identically by chance. That is worth ' +
        'more than it sounds. It means nobody queried a database, and nobody had access to the ' +
        'mortgage system: somebody got hold of a file that this organisation produces on purpose ' +
        'every month. The question changes from who broke in to where that file goes, and the ' +
        'August file holds 9,412 rows, so the twenty in the email are not the extent of anything.',
      standIn:
        'Those seven fields appear together in exactly one place: the monthly Broker Introduced ' +
        'Lending report. And the column order in the sample matches the report, which two systems ' +
        'would not do by chance. So nobody queried a database and nobody got into the mortgage ' +
        'system. Somebody got a file we produce deliberately every month. The August one is 9,412 ' +
        'rows, so twenty is not the extent of this.',
      commandOptions: [
        { command: 'head -1 /evidence/disclosure/sample.csv; head -1 /var/reports/broker-introduced-2026-08.csv', correct: true, teaches: CORRECT_STEP },
        { command: 'grep -rl "affordability_band" /var/reports/ | head', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mortgage-reporting', ...STATUS_CHECK },
        { command: 'cat /var/reports/broker-introduced-2026-08.csv', ...DUMP_ALL },
        { command: 'grep -c . /var/reports/broker-introduced-2026-08.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'Find which report contains all of those fields together, and compare the column order.',
      guidance:
        'Those extra fields come from somewhere. Ask which report has all of them.',
    },
    {
      eventId: 'ev.4',
      verdict: 'malicious',
      stage: 'exfiltration',
      critical: true,
      techniques: ['T1530'],
      firstResponder: 'cloud-security',
      alsoAppropriate: ['ir-lead', 'mitigation-specialist'],
      correctActions: ['act.iam-audit', 'act.corroborate'],
      outOfLaneActions: ['act.revoke-key', 'act.attribute-named', 'act.dismiss', 'act.reset-password'],
      escalateTo: ['ir-lead', 'mitigation-specialist'],
      why:
        'Nobody was attacked. A change on 14 January opened the container to public read so the ' +
        'broker portal integration could be tested, the testing finished on 22 January, and the ' +
        'change was never reversed. Read the description rather than skipping it, because it is ' +
        'the most useful sentence available: somebody wrote down why they were opening it and ' +
        'implicitly when it should close, and no part of the process was listening. Eight monthly ' +
        'reports have been written into an open container since February, each one added by a job ' +
        'doing exactly its job. This is not a failure anybody will feel proud of finding and it is ' +
        'the commonest way large amounts of personal data actually leave organisations: not stolen ' +
        'but published, by accident, months ago, and then found by a stranger.',
      standIn:
        'Nobody attacked us. Change CHG-9902 on 14 January set the container to public read for ' +
        'broker portal integration testing. Testing finished on 22 January and it was never put ' +
        'back. Eight monthly reports have been written into an open container since February, each ' +
        'by a job doing exactly what it was built to do. Nobody stole this. We published it in ' +
        'January and found out in September.',
      commandOptions: [
        { command: 'grep -iE "CHG-9902|public|open read" /var/log/cloud/policy-changes.log', correct: true, teaches: CORRECT_STEP },
        { command: 'aws s3api get-bucket-policy --bucket fenmarch-broker-reports', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status report-writer', ...STATUS_CHECK },
        { command: 'cat /var/log/cloud/policy-changes.log', ...DUMP_ALL },
        { command: 'aws s3api put-public-access-block --bucket fenmarch-broker-reports', ...MUTATE },
      ],
      commandNudge:
        'Check who can read the container those reports are written to, and when that changed.',
      guidance:
        'The file left somehow. Ask whether anybody needed to break in to get it.',
    },
    {
      eventId: 'ev.5',
      verdict: 'malicious',
      stage: 'exfiltration',
      critical: true,
      techniques: ['T1530'],
      firstResponder: 'network-analyst',
      alsoAppropriate: ['forensics', 'ir-lead'],
      correctActions: ['act.flow-map', 'act.probe-pattern'],
      outOfLaneActions: ['act.contact-attacker', 'act.attribute-named', 'act.isolate', 'act.dismiss'],
      escalateTo: ['ir-lead', 'mitigation-specialist'],
      why:
        'The number nobody wants and everybody needs. Four hundred and twelve downloads from 61 ' +
        'addresses since February, of which nine addresses are the broker portal and account for ' +
        '38. That leaves 52 unrecognised addresses and 374 downloads, and the first of them was on ' +
        '11 February, eighteen days after the container was opened, which says the internet finds ' +
        'open storage in under three weeks without anybody targeting anyone. Two things follow and ' +
        'both belong in the readout. The forum post on 19 August is one consequence of this and ' +
        'not the whole of it, so treating the incident as bounded by what the researcher found is ' +
        'wrong by 373 downloads. And the exposure period is seven months rather than three weeks, ' +
        'which is the number the regulator will ask for and is not the number anybody would guess ' +
        'from the email that started this.',
      standIn:
        'Four hundred and twelve downloads from 61 addresses since February. Nine of those are the ' +
        'broker portal and account for 38. That leaves 52 addresses and 374 downloads we cannot ' +
        'account for, and the first was 11 February, eighteen days after we opened it. Nobody had ' +
        'to target us; the internet finds open storage in under three weeks. And the forum post is ' +
        'one consequence, not the whole thing. Seven months of exposure, not three weeks.',
      commandOptions: [
        { command: "awk '$4==\"GET\" && $6==200 {print $2}' /var/log/cloud/container-access.log | sort | uniq -c | sort -rn", correct: true, teaches: CORRECT_STEP },
        { command: "awk '$4==\"GET\" && $6==200' /var/log/cloud/container-access.log | wc -l", correct: true, teaches: ALSO_WORKS },
        { command: 'nmap -Pn 203.0.113.90', ...TOUCH_ATTACKER },
        { command: 'cat /var/log/cloud/container-access.log', ...DUMP_ALL },
        { command: 'netstat -an | grep 443', ...WRONG_TARGET },
      ],
      commandNudge:
        'Count the downloads from that container and split them by whether the address is ours.',
      guidance:
        'It was open for seven months. Ask who actually took a copy.',
    },
    {
      eventId: 'ev.9',
      verdict: 'malicious',
      stage: 'exfiltration',
      critical: true,
      techniques: ['T1530'],
      firstResponder: 'forensics',
      alsoAppropriate: ['cloud-security', 'ir-lead'],
      correctActions: ['act.preserve', 'act.chain'],
      outOfLaneActions: ['act.contact-attacker', 'act.attribute-named', 'act.dismiss', 'act.reimage-now'],
      escalateTo: ['ir-lead', 'mitigation-specialist'],
      why:
        'Twenty becomes 9,412, and the sample everybody has been reasoning from turns out to be a ' +
        'courtesy. The posted file matches the August report exactly, header row and trailing ' +
        'newline included, which is what a byte-for-byte match is worth: it is not a file like ' +
        'ours, it is ours. The account number column is present and unredacted, so the researcher ' +
        'removed it before sending and the forum did not. And the creation timestamp of 01:04 on 1 ' +
        'August, four minutes after the report job runs, says the file was taken almost as soon as ' +
        'it was written rather than found later, which means somebody was watching that container ' +
        'rather than stumbling into it. Hash it and record the retrieval properly now, because ' +
        'this is the artefact the regulator and any subsequent claim will turn on, and a copy ' +
        'pulled off a forum with no custody record is an assertion rather than evidence. Say the ' +
        'number plainly in the readout: 9,412 members, with account numbers, and one month of ' +
        'eight.',
      standIn:
        'The posted file is the whole thing. Nine thousand four hundred and twelve rows, matching ' +
        'the August report byte for byte including the header and the trailing newline, so it is ' +
        'not a file like ours, it is ours. Account numbers present and unredacted, which the ' +
        'researcher removed and the forum did not. Created 01:04 on 1 August, four minutes after ' +
        'the job runs, so somebody was watching that container rather than stumbling on it. Hashed ' +
        'and custody recorded, because this is what the regulator will turn on. Nine thousand four ' +
        'hundred and twelve, with account numbers, and that is one month of eight.',
      commandOptions: [
        { command: 'sha256sum /evidence/forum/attachment.csv /var/reports/broker-introduced-2026-08.csv', correct: true, teaches: CORRECT_STEP },
        { command: 'wc -l /evidence/forum/attachment.csv && head -1 /evidence/forum/attachment.csv', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status report-writer', ...STATUS_CHECK },
        { command: 'cat /evidence/forum/attachment.csv', ...DUMP_ALL },
        { command: 'grep -c . /evidence/forum/attachment.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'Compare the posted file against our own August report, and count its rows.',
      guidance:
        'You have twenty records. Ask how many the posted file actually holds.',
    },
    {
      eventId: 'ev.6',
      verdict: 'benign-true-positive',
      firstResponder: 'soc-operator',
      alsoAppropriate: ['ir-lead', 'forensics'],
      correctActions: ['act.dismiss', 'act.investigate-hold'],
      outOfLaneActions: ['act.contact-attacker', 'act.attribute-named', 'act.triage-high', 'act.isolate'],
      escalateTo: ['ir-lead'],
      why:
        'The sender is not a threat and is owed a reply. They wrote from an address that resolves, ' +
        'signed with a name and a page that both check out, referenced two prior disclosures that ' +
        'are publicly documented, redacted the account number field in the sample, named the forum ' +
        'and thread, and asked for nothing. No payment, no deadline, no threat, no link. The point ' +
        'worth taking from this row is which of those facts did the work, because it is not the ' +
        'university address, which anybody can obtain, and not the politeness, which any competent ' +
        'extortionist manages. It is that they proved the claim before asking for anything, and ' +
        'redacted the field that would have made the sample useful to somebody else. Route the ' +
        'reply through the lead and legal rather than answering directly, not because the sender ' +
        'is suspect but because what this organisation says next is a legal position.',
      standIn:
        'The sender is fine and we owe them an answer. Address resolves, name and department page ' +
        'check out, two prior disclosures that are publicly documented, account numbers redacted in ' +
        'the sample, forum and thread named, and they asked for nothing. What tells me that is not ' +
        'the university address, which anybody can get, and not the politeness, which extortionists ' +
        'manage fine. It is that they proved it before asking for anything and redacted the field ' +
        'that would have made the sample useful to somebody else. Reply goes through the lead and ' +
        'legal.',
      commandOptions: [
        { command: 'grep -iE "^From:|^Reply-To:|^Return-Path:" /evidence/disclosure/message.eml', correct: true, teaches: CORRECT_STEP },
        { command: 'grep -icE "bitcoin|payment|deadline|publish" /evidence/disclosure/message.eml', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mailgw', ...STATUS_CHECK },
        { command: 'cat /evidence/disclosure/message.eml', ...DUMP_ALL },
        { command: 'curl -s http://203.0.113.90/thread/8812', ...TOUCH_ATTACKER },
      ],
      commandNudge:
        'Read the message again and list what the sender actually asked for.',
      guidance:
        'Ask what this person wants. Then ask what a criminal would have asked for.',
    },
    {
      eventId: 'ev.7',
      verdict: 'malicious',
      stage: 'exfiltration',
      firstResponder: 'mitigation-specialist',
      alsoAppropriate: ['ir-lead', 'cloud-security'],
      correctActions: ['act.contain-scoped', 'act.compensating-control', 'act.check-rollback', 'act.sequence-remedy'],
      outOfLaneActions: ['act.isolate', 'act.reset-password', 'act.attribute-named', 'act.reimage-now'],
      escalateTo: ['ir-lead'],
      why:
        'Closing the container is obviously right and is not free, which is the whole of this row. ' +
        'The broker portal pulls that report at 01:00 and loads the dashboard 340 mortgage brokers ' +
        'use to track their own cases, and the integration has never had a credential because it ' +
        'never needed one. So closing public read tonight breaks the dashboard tomorrow unless ' +
        'somebody issues that credential first, and month end is Thursday. Sequence it in that ' +
        'order rather than the dramatic one: issue the credential, confirm the 01:00 job ' +
        'authenticates with it, then close public read, and have the rollback written before ' +
        'either. What must not wait for any of it is the clock. The 72 hour regulatory ' +
        'notification runs from becoming aware, which was this morning, and the exposure is seven ' +
        'months of monthly reports rather than one file, so legal need the download figures and ' +
        'the February start date now and not after the technical work is tidy. Left undone and ' +
        'said out loud: 374 downloads went somewhere and nothing recalls them, so closing the ' +
        'container ends the exposure and does nothing about the copies.',
      standIn:
        'Closing it is right and it is not free. The broker portal pulls that report at 01:00 for a ' +
        'dashboard 340 brokers use, and that integration has never had a credential because it ' +
        'never needed one. So: issue the credential, confirm the 01:00 job authenticates, then ' +
        'close public read, rollback written first, and month end is Thursday. What does not wait ' +
        'is the clock. Seventy-two hours runs from this morning, the exposure is seven months of ' +
        'monthly reports, and legal need the download numbers and the February date now. And ' +
        'closing it ends the exposure and does nothing about 374 copies.',
      commandNudge:
        'Find out what else reads that container before you close it.',
    },
    {
      eventId: 'ev.8',
      verdict: 'false-positive',
      firstResponder: 'soc-operator',
      alsoAppropriate: ['ir-lead'],
      correctActions: ['act.dismiss'],
      outOfLaneActions: ['act.contact-attacker', 'act.declare', 'act.triage-high', 'act.attribute-named'],
      escalateTo: [],
      why:
        'Two messages, one morning, and only one of them is worth anything, which makes this the ' +
        'most useful comparison a beginner gets all day. This one claims a serious breach, says ' +
        'the database has been obtained, and promises publication in 48 hours unless a fee is ' +
        'paid. It attaches nothing. It names no system, no record count, no date and no forum, and ' +
        'the same wording appears in a sector warning published in June. Notice what is not the ' +
        'discriminator: it is not tone, spelling or plausibility, and it is not that the claim ' +
        'happens to be false, because today the claim is largely true and this sender still knows ' +
        'nothing. It is that they demanded before they demonstrated. Somebody who has your data ' +
        'can prove it in one line and will, because proof is what makes the demand work. Close it, ' +
        'keep it, and do not reply: a reply confirms a live mailbox, and 41 transfers to that ' +
        'address say enough people do reply to make sending it worthwhile.',
      standIn:
        'Second one is a scam and it is a useful pair with the first. Claims a serious breach, says ' +
        'they have the database, publication in 48 hours unless we pay. Attaches nothing. No ' +
        'system, no record count, no date, no forum, and the wording is in a sector warning from ' +
        'June. What tells us is not tone or spelling, and not that the claim is false, because ' +
        'today it is nearly true and this sender still knows nothing. They demanded before they ' +
        'demonstrated. Anybody who really has it proves it in one line, because the proof is what ' +
        'makes the demand work. Closing it, keeping it, not replying.',
      commandOptions: [
        { command: 'grep -icE "bitcoin|wallet|48 hours|fee|publish" /evidence/disclosure/second-message.eml', correct: true, teaches: CORRECT_STEP },
        { command: 'grep -iE "^Content-Disposition: attachment" /evidence/disclosure/second-message.eml || echo "no attachments"', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mailgw', ...STATUS_CHECK },
        { command: 'cat /evidence/disclosure/second-message.eml', ...DUMP_ALL },
        { command: 'curl -s http://203.0.113.61/pay', ...TOUCH_ATTACKER },
      ],
      commandNudge:
        'Compare the two messages on one question: which of them proved anything?',
      guidance:
        'Both say we have been breached. Ask which one showed you something.',
    },
  ],
};
