/**
 * Scenario 69: The Fifth Warning.
 *
 * The sector body has issued five advisories this year. Four came to nothing.
 * This one has no indicators in it at all.
 *
 * WHAT THIS TEACHES
 *
 * What to do with intelligence that cannot be pasted into a tool.
 *
 * An advisory with a block of addresses and hashes is easy to consume and
 * usually worth little, because infrastructure is cheap to change. This one
 * describes a technique chain and nothing else: a valid account on a
 * freight-forwarding portal, a mailbox rule that hides replies, and invoice
 * manipulation. There is nothing to search for and everything to hunt for, and
 * the work of turning the second into the first is the job this seat exists to
 * do.
 *
 * THE BASE RATE IS NOT AN ARGUMENT
 *
 * Four of five advisories this year produced nothing here, which is exactly the
 * reasoning that gets the fifth ignored, and it is wrong in a specific way: two
 * of the four were entirely real somewhere else, and the floor's own experience
 * measures relevance to this organisation rather than truth. A warning being
 * unactioned four times is a fact about the warnings and about this floor, and
 * it says nothing about the fifth.
 *
 * WHAT THE HUNT ACTUALLY PRODUCES
 *
 * Two things, and only one of them is the campaign. It also finds a problem
 * that has been sitting there since March and has nothing to do with the
 * advisory, which is the ordinary and undersold return on hunting: the
 * hypothesis does not have to be right for the search to be worth running.
 */

import type { Scenario, ScenarioTruth } from '@soc/shared';

import { COMMON_ACTIONS } from './actions.js';
import {
  ALSO_WORKS,
  COUNT_ONLY,
  CORRECT_STEP,
  DUMP_ALL,
  MUTATE,
  STATUS_CHECK,
  TOUCH_ATTACKER,
  WRONG_TARGET,
} from './distractors.js';

const ID = 'the-fifth-warning';

export const THE_FIFTH_WARNING: Scenario = {
  id: ID,
  title: 'The Fifth Warning',
  difficulty: 'advanced',
  durationMinutes: 75,
  situation:
    'It is 10:00 at Ardal Freight. The sector information sharing body has issued its fifth ' +
    'advisory of the year. It contains no addresses, no hashes and no domains, and the last four ' +
    'came to nothing here.',
  roles: [
    'soc-operator',
    'log-analyst',
    'network-analyst',
    'forensics',
    'cloud-security',
    'threat-intel',
    'detection-engineer',
    'fusion-analyst',
    'mitigation-specialist',
    'ir-lead',
  ],
  actions: COMMON_ACTIONS,

  events: [
    {
      id: 'ev.1',
      atSeconds: 0,
      surface: 'alert-queue',
      summary: 'An advisory describing a technique chain, with nothing to search for',
      detail:
        'Sector advisory SA-2026-131 describes a campaign against freight and logistics operators ' +
        'in three steps: access obtained to a freight-forwarding portal using valid credentials ' +
        'bought or phished, a client-side mailbox rule created to move and mark as read any reply ' +
        'containing payment terms, and alteration of bank details on outbound invoices. It lists no ' +
        'addresses, hashes or domains. Rule history: no rule can be written from this document.',
      source: 'sector advisory SA-2026-131',
      claimedSeverity: 'high',
    },
    {
      id: 'ev.2',
      atSeconds: 160,
      surface: 'alert-queue',
      summary: 'What became of the previous four',
      detail:
        'SA-2026-044 in February described ransomware against warehouse control systems and matched ' +
        'nothing here. SA-2026-071 in April described a router vulnerability Ardal does not run. ' +
        'SA-2026-098 in June described invoice fraud at two named operators, both of whom later ' +
        'confirmed losses. SA-2026-115 in July described a credential broker selling logistics ' +
        'portal access, and three operators subsequently reported intrusions. Nothing was found at ' +
        'Ardal on any of the four.',
      source: 'advisory history',
      claimedSeverity: 'medium',
    },
    {
      id: 'ev.3',
      atSeconds: 320,
      surface: 'raw-log',
      summary: 'Of the three steps, one is fully visible, one partly, one not at all',
      detail:
        'Portal authentication is logged in full and retained for a year. Mailbox rule creation is ' +
        'recorded in the mail platform audit log, which is retained for 90 days and does not record ' +
        'the rule\'s conditions, only that a rule was created. Outbound invoice content is not ' +
        'logged anywhere: invoices are generated by the finance system, rendered to PDF and sent, ' +
        'and no copy of the sent document is retained.',
      source: 'telemetry review',
      claimedSeverity: 'high',
    },
    {
      id: 'ev.4',
      atSeconds: 480,
      surface: 'cloud-audit',
      summary: 'Sixty-one accounts have client-side mailbox rules',
      detail:
        'A search of the mail platform finds 61 accounts with client-side rules that move messages ' +
        'and mark them read. Fifty-nine were created between 3 and 6 March, all within the mailbox ' +
        'migration window recorded in the change system, all by the migration service account, and ' +
        'all move messages to a folder named Archived Mail. Two were created by the account holders ' +
        'themselves, eleven days ago and eight days ago.',
      source: 'mail platform',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.5',
      atSeconds: 640,
      surface: 'raw-log',
      summary: 'The two rules move anything about money out of sight',
      detail:
        'Both rules were created from a web session. The audit record does not hold their ' +
        'conditions, but the mailboxes show the effect: in both, every received message whose ' +
        'subject contains invoice, remittance, payment or bank details sits in a folder named RSS ' +
        'Subscriptions, marked as read, and neither account holder has ever opened that folder. ' +
        'Fourteen such messages in one mailbox, nine in the other.',
      source: 'mail platform',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.6',
      atSeconds: 800,
      surface: 'network-flow',
      summary: 'Both accounts signed in from the freight-forwarding vendor\'s own address range',
      detail:
        'Both accounts authenticated to the mail platform from 198.51.100.140, eleven days ago and ' +
        'eight days ago, minutes before each rule was created. That address belongs to the hosting ' +
        'provider used by Ardal\'s freight-forwarding portal vendor, whose support staff ' +
        'legitimately connect from the same block and have done 400 times this year. Neither ' +
        'account holder was travelling. Both were at their desks.',
      source: '198.51.100.140',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.7',
      atSeconds: 960,
      surface: 'host-artefact',
      summary: 'The hunt turns up something else entirely',
      detail:
        'Reviewing mailbox configuration across the estate finds full delegate access on the ' +
        'accounts payable shared mailbox granted to r.senna, who left Ardal in March. The account ' +
        'was disabled on the leaving date and re-enabled on 2 April by a service desk ticket asking ' +
        'to "restore access for handover", then never disabled again. It has authenticated 40 times ' +
        'since, most recently in July, always from an office range.',
      source: 'mail platform',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.8',
      atSeconds: 1120,
      surface: 'alert-queue',
      summary: 'Two steps of three, and the third is the one nobody can see',
      detail:
        'Steps one and two of the advisory chain are present: portal credentials used from an ' +
        'unexpected source, and mailbox rules hiding payment correspondence. Step three, alteration ' +
        'of bank details on outbound invoices, cannot be observed because no copy of a sent invoice ' +
        'is retained. Twenty-three messages about payments have been hidden from two account ' +
        'holders across eleven days. No customer has reported a misdirected payment.',
      source: 'assessment',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.9',
      atSeconds: 1280,
      surface: 'alert-queue',
      summary: 'The vendor connects from that range four hundred times a year',
      detail:
        'The freight-forwarding portal vendor provides support to Ardal under contract and its staff ' +
        'connect from 198.51.100.140 routinely. Blocking the range stops portal support, which ' +
        'covers 900 daily bookings. The two affected staff work in accounts receivable and are ' +
        'mid-month. Ardal invoices roughly 1,200 customers a month, and the invoices sent in the ' +
        'last eleven days number 430.',
      source: 'commercial operations',
      claimedSeverity: 'critical',
    },
    {
      id: 'ev.10',
      atSeconds: 1440,
      surface: 'raw-log',
      summary: 'The mail audit log records that a rule exists and not what it does',
      detail:
        'Mailbox rule creation is audited, but the audit event carries only the account, the ' +
        'timestamp and the fact of creation. The conditions and actions are held client-side and ' +
        'are recoverable only by reading the mailbox. Retention on that audit stream is 90 days. No ' +
        'alert exists on rule creation, on rules that mark messages read, or on rules that target ' +
        'financial keywords.',
      source: 'detection coverage',
      claimedSeverity: 'high',
    },
    {
      id: 'ev.11',
      atSeconds: 1600,
      surface: 'alert-queue',
      summary: 'A rule from the March migration is flagged during the sweep',
      detail:
        'The sweep flags a rule on the account of a warehouse supervisor that moves messages to ' +
        'Archived Mail and marks them read. It was created on 4 March by the migration service ' +
        'account within the change window, is identical to 58 others created the same week, moves ' +
        'only messages older than 30 days, and the folder is visible in the mailbox and has been ' +
        'opened 200 times.',
      source: 'mail platform',
      claimedSeverity: 'medium',
    },
  ],
};

export const THE_FIFTH_WARNING_TRUTH: ScenarioTruth = {
  scenarioId: ID,
  narrative: [
    'Sector advisory SA-2026-131 describes a three step campaign against logistics operators: portal access with valid credentials, a mailbox rule hiding payment correspondence, and alteration of bank details on outbound invoices. It contains no indicators of any kind.',
    'Two Ardal accounts authenticated to the mail platform from 198.51.100.140 eleven and eight days ago, minutes before each created a client-side rule from a web session. Both account holders were at their desks at the time.',
    'That address belongs to the hosting provider used by Ardal\'s freight-forwarding portal vendor, whose support staff connect from the same block 400 times a year.',
    'Both mailboxes now hold every message about invoices, remittances, payments or bank details in a folder named RSS Subscriptions, marked as read: fourteen in one, nine in the other. Neither holder has ever opened that folder.',
    'The third step cannot be observed. Outbound invoices are rendered to PDF and sent, and no copy of a sent document is retained anywhere, so whether bank details were altered is not answerable from Ardal telemetry.',
    'Fifty-nine other accounts have rules that look superficially similar and are the March mailbox migration, created by the migration service account inside the change window.',
    'The hunt separately found full delegate access on the accounts payable shared mailbox belonging to somebody who left in March, disabled on their leaving date and re-enabled on 2 April by a ticket asking to restore access for handover. It has been used 40 times since and has nothing to do with the advisory.',
    'Four of the year\'s five advisories produced nothing at Ardal. Two of those four were entirely real elsewhere.',
  ],
  events: [
    {
      eventId: 'ev.1',
      verdict: 'malicious',
      stage: 'reconnaissance',
      firstResponder: 'soc-operator',
      alsoAppropriate: ['threat-intel', 'ir-lead'],
      correctActions: ['act.triage-high', 'act.investigate-hold'],
      outOfLaneActions: ['act.dismiss', 'act.tune', 'act.declare', 'act.attribute-named'],
      escalateTo: ['threat-intel', 'detection-engineer'],
      why:
        'An advisory with nothing in it to search for is the kind that gets filed, and the reason is ' +
        'structural rather than lazy: a floor is built to consume indicators, and this document ' +
        'contains three sentences of behaviour instead. Do not close it and do not declare on it ' +
        'either, because nothing here says anything has happened at Ardal. What it needs is a seat ' +
        'that can turn a described chain into questions this estate can answer, which is a ' +
        'different activity from triage and takes hours rather than minutes. Route it and say ' +
        'plainly that it is a hunt request rather than an alert, so that whoever picks it up is not ' +
        'measured against a response time it was never going to meet.',
      standIn:
        'Fifth sector advisory this year, and this one has no addresses, no hashes, no domains. Three ' +
        'sentences of behaviour. There is nothing to search for and nothing has happened here as ' +
        'far as I know, so I am not closing it and not declaring on it. This is a hunt request, not ' +
        'an alert, and it needs somebody who can turn a described chain into questions we can ' +
        'actually ask.',
      commandOptions: [
        { command: 'grep -icE "indicator|hash|domain|ip address" /evidence/advisory/SA-2026-131.txt', correct: true, teaches: CORRECT_STEP },
        { command: 'grep -nE "^Step|technique" /evidence/advisory/SA-2026-131.txt', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status siem', ...STATUS_CHECK },
        { command: 'cat /evidence/advisory/SA-2026-131.txt', ...DUMP_ALL },
        { command: 'grep -c . /evidence/advisory/SA-2026-131.txt', ...COUNT_ONLY },
      ],
      commandNudge:
        'Check whether the advisory contains anything a tool could search for.',
      guidance:
        'Ask what you would actually type into a search box from this document.',
    },
    {
      eventId: 'ev.2',
      verdict: 'benign-true-positive',
      firstResponder: 'threat-intel',
      alsoAppropriate: ['ir-lead', 'soc-operator'],
      correctActions: ['act.assess-actor', 'act.investigate-hold'],
      outOfLaneActions: ['act.dismiss', 'act.attribute-named', 'act.declare', 'act.tune'],
      escalateTo: ['detection-engineer', 'ir-lead'],
      why:
        'Four for nothing is the argument that will be made in the next ten minutes, and it has to ' +
        'be answered properly rather than overruled. Look at what the four actually were. February ' +
        'described ransomware against warehouse control systems Ardal does not operate. April ' +
        'described a router vulnerability Ardal does not run. Those two were correctly irrelevant, ' +
        'and a floor that ignored them was right. June described invoice fraud at two named ' +
        'operators who later confirmed losses, and July described a credential broker selling ' +
        'logistics portal access, after which three operators reported intrusions. Those two were ' +
        'entirely true and simply did not happen here yet. So the record is not four false alarms, ' +
        'it is two irrelevant, two real elsewhere, and nothing found here on any of them, which is ' +
        'a fact about relevance rather than about truth. Say that distinction out loud, because it ' +
        'is the whole reason the fifth deserves the hours, and note that this one describes the ' +
        'same crime as the June advisory against the same sector.',
      standIn:
        'Somebody is about to say four for nothing, so let me take those four properly. February was ' +
        'warehouse control systems we do not run. April was a router we do not have. Those two were ' +
        'correctly irrelevant and ignoring them was right. June was invoice fraud at two named ' +
        'operators who later confirmed losses. July was a broker selling logistics portal access ' +
        'and three operators then reported intrusions. Those two were true and just had not reached ' +
        'us. So it is not four false alarms, it is two irrelevant and two real elsewhere. And this ' +
        'one describes the same crime as June against the same sector.',
      commandNudge:
        'Look up each previous advisory and find out whether it was wrong or simply not about you.',
    },
    {
      eventId: 'ev.3',
      verdict: 'benign-true-positive',
      critical: true,
      firstResponder: 'log-analyst',
      alsoAppropriate: ['detection-engineer', 'threat-intel', 'ir-lead'],
      correctActions: ['act.timeline', 'act.corroborate'],
      outOfLaneActions: ['act.dismiss', 'act.tune', 'act.attribute-named', 'act.isolate'],
      escalateTo: ['cloud-security', 'threat-intel'],
      why:
        'This is the step that converts an advisory into work, and doing it first saves the rest of ' +
        'the day. Take the three described behaviours and ask, before searching for anything, what ' +
        'this estate could see if each were happening. Portal authentication is logged in full and ' +
        'kept for a year, so step one is answerable. Mailbox rule creation is audited for 90 days ' +
        'but the audit event does not record what the rule does, so step two is half answerable and ' +
        'the missing half has to come from the mailboxes themselves. Outbound invoice content is ' +
        'not retained at all, so step three cannot be answered from telemetry at any price. Knowing ' +
        'that before the hunt starts changes what gets hunted and, more importantly, tells the ' +
        'floor in advance which conclusion it will not be able to reach, which is the difference ' +
        'between reporting an unanswerable question and reporting a negative.',
      standIn:
        'Before anybody searches for anything: what could we see if each of these were happening. ' +
        'Portal authentication, logged in full, kept a year, so step one is answerable. Rule ' +
        'creation is audited 90 days but the event does not record what the rule does, so step two ' +
        'is half answerable and the other half has to come out of the mailboxes. Sent invoice ' +
        'content is not retained anywhere, so step three cannot be answered at any price. Worth ' +
        'knowing now, because it tells us which conclusion we will not be able to reach.',
      commandOptions: [
        { command: "awk -F, '{print $2, $5}' /var/log/telemetry/sources.csv | sort -u", correct: true, teaches: CORRECT_STEP },
        { command: 'grep -iE "retention|fields" /evidence/telemetry/mail-audit-schema.txt', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status siem', ...STATUS_CHECK },
        { command: 'cat /var/log/telemetry/sources.csv', ...DUMP_ALL },
        { command: 'grep -c . /var/log/telemetry/sources.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'For each described step, find out what telemetry exists and how long it is kept.',
      guidance:
        'Before you hunt, ask what you would be able to see if it were true.',
    },
    {
      eventId: 'ev.4',
      verdict: 'malicious',
      stage: 'defense-evasion',
      critical: true,
      techniques: ['T1564.008'],
      firstResponder: 'cloud-security',
      alsoAppropriate: ['log-analyst', 'fusion-analyst', 'ir-lead'],
      correctActions: ['act.iam-audit', 'act.corroborate'],
      outOfLaneActions: ['act.revoke-key', 'act.reset-password', 'act.attribute-named', 'act.dismiss'],
      escalateTo: ['ir-lead', 'fusion-analyst'],
      why:
        'Sixty-one is the number that would have been reported by anybody who stopped at the search, ' +
        'and it is almost entirely the March mailbox migration. Fifty-nine created between the ' +
        'third and the sixth of March, inside the change window, by the migration service account, ' +
        'all moving to a folder called Archived Mail. Two created by the account holders ' +
        'themselves, eleven and eight days ago. The split takes one query and it is the difference ' +
        'between an incident and a fortnight of pointless work. Note which properties did the ' +
        'separating, because they are reusable: who created it, when, and whether it sits inside a ' +
        'recorded change. None of those is about the rule itself, which is the point. The two that ' +
        'remain are not yet evidence of anything beyond somebody creating a rule on their own ' +
        'mailbox, which people do.',
      standIn:
        'Sixty-one accounts have these rules and 59 of them are the March migration: created between ' +
        'the third and sixth, inside the change window, by the migration service account, all ' +
        'moving to Archived Mail. Two were created by the account holders themselves, eleven and ' +
        'eight days ago. One query to split them, and it is the difference between an incident and ' +
        'two weeks of wasted work. What separated them was who, when, and whether it is inside a ' +
        'recorded change, none of which is about the rule. The two left are not evidence of much ' +
        'yet.',
      commandOptions: [
        { command: "awk -F, '$3==\"RULE_CREATE\" {print $4, substr($1,1,10)}' /var/log/mail/audit.csv | sort | uniq -c | sort -rn", correct: true, teaches: CORRECT_STEP },
        { command: "awk -F, '$3==\"RULE_CREATE\" && $4!=\"svc-mailmigrate\"' /var/log/mail/audit.csv", correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mail-platform', ...STATUS_CHECK },
        { command: 'cat /var/log/mail/audit.csv', ...DUMP_ALL },
        { command: 'grep -c RULE_CREATE /var/log/mail/audit.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'Split the rules by who created them and whether a change record covers it.',
      guidance:
        'Sixty-one is a lot. Ask what most of them have in common.',
    },
    {
      eventId: 'ev.5',
      verdict: 'malicious',
      stage: 'defense-evasion',
      critical: true,
      techniques: ['T1564.008'],
      firstResponder: 'log-analyst',
      alsoAppropriate: ['forensics', 'fusion-analyst', 'ir-lead'],
      correctActions: ['act.timeline', 'act.corroborate'],
      outOfLaneActions: ['act.reset-password', 'act.attribute-named', 'act.dismiss', 'act.isolate'],
      escalateTo: ['ir-lead', 'threat-intel'],
      why:
        'The audit log will not say what these rules do, so the mailbox has to. In both, every ' +
        'received message whose subject mentions invoices, remittances, payments or bank details is ' +
        'sitting in a folder called RSS Subscriptions, marked as read, and neither account holder ' +
        'has ever opened that folder. That is not a filing preference. RSS Subscriptions is a ' +
        'default folder nobody uses and nobody looks in, marking as read defeats the unread count ' +
        'that would otherwise make somebody curious, and the keyword set is precisely the ' +
        'correspondence a customer would send if they had queried a payment. Twenty-three messages ' +
        'across eleven days that two people were supposed to read and did not. This is step two of ' +
        'the advisory chain, arriving in the exact form described, and that correspondence is worth ' +
        'reading before anything else happens: it is the only place a customer who noticed ' +
        'something would have said so.',
      standIn:
        'The audit will not tell us what the rules do, so I went to the mailboxes. In both, every ' +
        'message about invoices, remittances, payments or bank details is in a folder called RSS ' +
        'Subscriptions, marked read, and neither of them has ever opened that folder. That is not ' +
        'filing. It is a default folder nobody looks in, marking as read kills the unread count, ' +
        'and those keywords are exactly what a customer sends when they query a payment. ' +
        'Twenty-three messages in eleven days that two people were meant to read. Somebody should ' +
        'read them now, because that is the only place a customer who noticed would have said so.',
      commandOptions: [
        { command: "awk -F, '$3==\"RSS Subscriptions\" {print $2, $5}' /evidence/mail/folder-contents.csv", correct: true, teaches: CORRECT_STEP },
        { command: 'grep -icE "invoice|remittance|payment|bank" /evidence/mail/folder-contents.csv', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mail-platform', ...STATUS_CHECK },
        { command: 'cat /evidence/mail/folder-contents.csv', ...DUMP_ALL },
        { command: 'rm -rf /evidence/mail/rss-subscriptions/', ...MUTATE },
      ],
      commandNudge:
        'The audit does not record the rule conditions. Look at where messages actually ended up.',
      guidance:
        'You cannot see what the rule says. Ask what the mailbox looks like as a result.',
    },
    {
      eventId: 'ev.6',
      verdict: 'malicious',
      stage: 'initial-access',
      critical: true,
      techniques: ['T1078.004'],
      firstResponder: 'network-analyst',
      alsoAppropriate: ['fusion-analyst', 'ir-lead'],
      correctActions: ['act.flow-map', 'act.probe-pattern'],
      outOfLaneActions: ['act.isolate', 'act.contact-attacker', 'act.attribute-named', 'act.dismiss'],
      escalateTo: ['ir-lead', 'mitigation-specialist'],
      why:
        'The address is the strongest and most awkward fact on the board. Both accounts authenticated ' +
        'from 198.51.100.140 minutes before each rule was created, and both holders were at their ' +
        'desks at the time, so somebody else was using their credentials. That much is settled. ' +
        'What is not settled is what the address means, because it belongs to the hosting provider ' +
        'used by the freight-forwarding portal vendor, whose support staff connect from the same ' +
        'block 400 times a year with a contract that permits it. Three readings fit: the vendor is ' +
        'compromised and the attacker is inside their estate, an unrelated tenant of the same ' +
        'hosting provider is the source, or somebody chose that block precisely because traffic ' +
        'from it is expected here. Report the address as a strong indicator of unauthorised access ' +
        'and explicitly not as an accusation against the vendor, and get the vendor called by ' +
        'somebody who can ask a contractual question rather than by this floor.',
      standIn:
        'Both accounts authenticated from one address minutes before each rule was created, and both ' +
        'people were at their desks. Somebody else was using their credentials, and that is ' +
        'settled. What the address means is not. It belongs to the hosting provider our portal ' +
        'vendor uses, and their support staff connect from that block 400 times a year under ' +
        'contract. Could be the vendor compromised, could be another tenant of the same provider, ' +
        'could be somebody who picked that block because traffic from it is expected here. Strong ' +
        'indicator of unauthorised access, not an accusation against the vendor, and somebody ' +
        'senior needs to call them.',
      commandOptions: [
        { command: "awk -F, '$5==\"198.51.100.140\" {print $1, $4}' /var/log/mail/signin.csv", correct: true, teaches: CORRECT_STEP },
        { command: 'grep -c "198.51.100.140" /var/log/portal/vendor-support.log', correct: true, teaches: ALSO_WORKS },
        { command: 'nmap -Pn 198.51.100.140', ...TOUCH_ATTACKER },
        { command: 'cat /var/log/mail/signin.csv', ...DUMP_ALL },
        { command: 'netstat -an | grep 443', ...WRONG_TARGET },
      ],
      commandNudge:
        'Find where those two sessions came from, and whether that address is known to the estate.',
      guidance:
        'Somebody made those rules. Ask where they were sitting.',
    },
    {
      eventId: 'ev.7',
      verdict: 'malicious',
      stage: 'persistence',
      critical: true,
      techniques: ['T1098.002'],
      firstResponder: 'forensics',
      alsoAppropriate: ['cloud-security', 'ir-lead'],
      correctActions: ['act.preserve', 'act.chain'],
      outOfLaneActions: ['act.attribute-named', 'act.reset-password', 'act.dismiss', 'act.reimage-now'],
      escalateTo: ['ir-lead', 'mitigation-specialist'],
      why:
        'Not the campaign, and worth the morning on its own. Full delegate access on the accounts ' +
        'payable shared mailbox held by somebody who left in March: disabled correctly on their ' +
        'leaving date, then re-enabled on 2 April by a service desk ticket asking to restore access ' +
        'for handover, and never disabled again. Forty authentications since, most recently in ' +
        'July, always from an office range, which is the detail that makes it messy rather than ' +
        'sinister: somebody has been using it, and an office range means it is probably a ' +
        'colleague continuing to do a job with a departed person\'s access rather than an intruder. ' +
        'That is still full delegate access to accounts payable held by a non-employee for five ' +
        'months. The general point belongs in the debrief and is the honest defence of hunting: the ' +
        'hypothesis was about an advisory and the search found something unrelated, which is the ' +
        'ordinary return on looking properly at an estate nobody has looked at in a while.',
      standIn:
        'This is not the campaign and it was worth the morning anyway. Full delegate access on the ' +
        'accounts payable shared mailbox belonging to somebody who left in March. Disabled properly ' +
        'on their leaving date, re-enabled on 2 April by a ticket asking to restore access for ' +
        'handover, never disabled again. Forty authentications since, always from an office range, ' +
        'which probably means a colleague carrying on with a leaver\'s access rather than an ' +
        'intruder. It is still five months of accounts payable delegate access held by a ' +
        'non-employee. We went looking for one thing and found another, and that is what hunting ' +
        'is for.',
      commandOptions: [
        { command: "awk -F, '$3==\"DELEGATE\" {print $2, $4, $5}' /var/log/mail/permissions.csv", correct: true, teaches: CORRECT_STEP },
        { command: 'join -1 1 -2 1 /evidence/hr/leavers.txt /evidence/mail/enabled-accounts.txt', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mail-platform', ...STATUS_CHECK },
        { command: 'cat /var/log/mail/permissions.csv', ...DUMP_ALL },
        { command: 'net user r.senna /active:no /domain', ...MUTATE },
      ],
      commandNudge:
        'While reviewing mailbox configuration, check delegate access against the leavers list.',
      guidance:
        'You are already looking at mailbox settings. Ask what else is wrong with them.',
    },
    {
      eventId: 'ev.8',
      verdict: 'malicious',
      stage: 'collection',
      critical: true,
      techniques: ['T1565.001'],
      firstResponder: 'threat-intel',
      alsoAppropriate: ['fusion-analyst', 'ir-lead'],
      correctActions: ['act.assess-actor', 'act.predict', 'act.corroborate'],
      outOfLaneActions: ['act.attribute-named', 'act.dismiss', 'act.declare', 'act.isolate'],
      escalateTo: ['ir-lead', 'mitigation-specialist'],
      why:
        'Two of the three described steps are present in the form described, and the third cannot be ' +
        'observed. That has to be stated as three separate claims rather than one, because they ' +
        'carry different confidence. Steps one and two are established: credentials used from a ' +
        'source neither holder was at, and rules hiding exactly the correspondence the advisory ' +
        'names. Step three is not refuted, it is unobservable, because no copy of a sent invoice is ' +
        'retained anywhere, and the difference between not found and cannot be looked for is the ' +
        'single most important sentence in the report. And there is a second-order finding hiding ' +
        'in the twenty-three hidden messages: they are the mechanism by which nobody has reported a ' +
        'misdirected payment. A customer who noticed and wrote in would have written into the ' +
        'folder nobody opens, so the absence of complaints is not evidence that nothing happened, ' +
        'it is a predicted consequence of the technique. Assess it as consistent with the advisory ' +
        'chain at high confidence, name the unobservable step, and predict the confirmation route: ' +
        'read the hidden messages and call the customers.',
      standIn:
        'Two of three steps present in the form described, and the third we cannot see. Three ' +
        'separate claims, three different confidences. Steps one and two are established. Step ' +
        'three is not refuted, it is unobservable, because we keep no copy of a sent invoice, and ' +
        'not found versus cannot be looked for is the most important sentence in this report. And ' +
        'the twenty-three hidden messages are why nobody has reported a misdirected payment: a ' +
        'customer who noticed wrote into the folder nobody opens. No complaints is a predicted ' +
        'consequence of the technique, not evidence it did not happen. Consistent with the ' +
        'advisory, high confidence, and the way to confirm it is to read those messages and phone ' +
        'the customers.',
      commandNudge:
        'Map what you observed onto the advisory\'s steps, and mark which one you had no way of ' +
        'seeing.',
    },
    {
      eventId: 'ev.9',
      verdict: 'malicious',
      stage: 'collection',
      firstResponder: 'mitigation-specialist',
      alsoAppropriate: ['ir-lead'],
      correctActions: ['act.contain-scoped', 'act.compensating-control', 'act.check-rollback', 'act.sequence-remedy'],
      outOfLaneActions: ['act.isolate', 'act.reset-password', 'act.attribute-named', 'act.reimage-now'],
      escalateTo: ['ir-lead'],
      why:
        'The obvious block is the wrong shape. That address range carries the portal vendor\'s ' +
        'support for 900 daily bookings, and blocking it stops support for a system the business ' +
        'runs on, on the strength of an address that may belong to an unrelated tenant of the same ' +
        'hosting provider. The narrow moves are all elsewhere and none of them needs the address ' +
        'question answered: delete the two rules and preserve their effects first, reset those two ' +
        'accounts and revoke their sessions, and require multi-factor for mail platform sign-in ' +
        'from outside office ranges, which is a control that should exist and inconveniences ' +
        'nobody at a desk. Then the thing that actually bounds the damage, which is not technical: ' +
        '430 invoices have gone out in eleven days, no copy of any of them is retained, and the ' +
        'only way to establish whether bank details were altered is to call customers and ask what ' +
        'account they were told to pay into. That is a finance conversation this floor cannot have ' +
        'and must ask for tonight rather than tomorrow. Deliberately left undone: the vendor range ' +
        'stays open, the departed account stays enabled until accounts payable confirm who has ' +
        'been using it, because disabling it mid-month without asking breaks a payment run.',
      standIn:
        'Do not block that range. It carries the portal vendor\'s support for 900 bookings a day and ' +
        'the address may belong to an unrelated tenant. Everything useful is elsewhere: preserve ' +
        'and then delete the two rules, reset those accounts and kill their sessions, and require ' +
        'multi-factor on mail sign-in from outside office ranges, which should exist anyway and ' +
        'costs nobody at a desk anything. Then the part that actually bounds this and is not ' +
        'technical: 430 invoices went out in eleven days, we keep no copy of any of them, and the ' +
        'only way to know whether bank details were changed is to phone customers and ask what ' +
        'account they were told to pay. Finance has to start that tonight. Left undone: the vendor ' +
        'range, and the leaver\'s account until accounts payable tell us who has been using it.',
      commandNudge:
        'Find out what else depends on that address range before proposing to block it.',
    },
    {
      eventId: 'ev.10',
      verdict: 'malicious',
      stage: 'defense-evasion',
      techniques: ['T1564.008'],
      firstResponder: 'detection-engineer',
      alsoAppropriate: ['log-analyst', 'ir-lead'],
      correctActions: ['act.propose-rule', 'act.backtest'],
      outOfLaneActions: ['act.write-rule', 'act.dismiss', 'act.isolate', 'act.attribute-named'],
      escalateTo: ['ir-lead'],
      why:
        'The audit stream records that a rule was created and not what it does, which is the reason ' +
        'this took a mailbox review instead of a query, and it is a gap that cannot be closed by ' +
        'writing a better rule against the data that exists. Propose the two things the platform ' +
        'can actually support and be honest about which is cheap. Alerting on client-side rule ' +
        'creation is trivial and would have fired 61 times in six months, 59 of them in one week ' +
        'and all of those attributable to a service account inside a change window, so scoped to ' +
        'rules created by a human it is roughly two alerts a year and worth having. Recovering rule ' +
        'conditions requires reading mailboxes, which is a scheduled sweep rather than a detection ' +
        'and needs a privacy conversation before it is built. Say the third thing too, because it ' +
        'is the one nobody will raise: 90 day retention on the mail audit stream means a rule ' +
        'created four months ago is invisible to this method entirely, and nothing here would have ' +
        'found it.',
      standIn:
        'The audit records that a rule was created and not what it does, which is why this took a ' +
        'mailbox review rather than a query, and no better rule against the data we have fixes ' +
        'that. Two proposals. Alerting on client-side rule creation is trivial: 61 in six months, ' +
        '59 of them one week of migration by a service account, so scoped to human-created rules ' +
        'it is about two alerts a year. Recovering conditions means reading mailboxes, which is a ' +
        'scheduled sweep and needs a privacy conversation first. And the thing nobody will raise: ' +
        'retention on that audit stream is 90 days, so a rule made four months ago is invisible to ' +
        'all of this.',
      commandOptions: [
        { command: "awk -F, '$3==\"RULE_CREATE\"' /var/log/mail/audit.csv | wc -l", correct: true, teaches: CORRECT_STEP },
        { command: 'grep -iE "retention" /evidence/telemetry/mail-audit-schema.txt', correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mail-platform', ...STATUS_CHECK },
        { command: 'cat /var/log/mail/audit.csv', ...DUMP_ALL },
        { command: 'grep -c . /var/log/mail/audit.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'Count how often a human creates a mailbox rule, then decide whether that is alertable.',
      guidance:
        'Ask what the audit log records about a rule, and what it leaves out.',
    },
    {
      eventId: 'ev.11',
      verdict: 'benign-true-positive',
      firstResponder: 'soc-operator',
      alsoAppropriate: ['cloud-security', 'log-analyst'],
      correctActions: ['act.dismiss'],
      outOfLaneActions: ['act.triage-high', 'act.isolate', 'act.reset-password', 'act.declare'],
      escalateTo: [],
      why:
        'A rule that moves messages and marks them read, on the morning the floor has learned that a ' +
        'rule which moves messages and marks them read is an intrusion. Four checks close it and ' +
        'each maps to something that convicted the other two: created on 4 March by the migration ' +
        'service account inside the recorded change window, identical to 58 others from the same ' +
        'week, moves only messages older than thirty days, and the destination folder is visible in ' +
        'the mailbox and has been opened 200 times. That last one is the cleanest discriminator ' +
        'available and costs nothing to check, because the whole purpose of the two malicious rules ' +
        'was that nobody would look in the folder. Close it. The row exists because a sweep that ' +
        'has just found something real will be run again across the estate by somebody who now ' +
        'believes the rule pattern is the finding, and 59 people will be asked to explain a ' +
        'mailbox setting they did not make.',
      standIn:
        'Moves messages and marks them read, and it is the March migration. Created 4 March by the ' +
        'migration service account inside the change window, identical to 58 others that week, only ' +
        'touches messages older than thirty days, and the destination folder is visible and has ' +
        'been opened 200 times. That last one is the cheapest check we have, because the entire ' +
        'point of the two bad rules was that nobody would look in the folder. Closing it, and ' +
        'somebody needs to say that before 59 people get asked to explain a setting they did not ' +
        'make.',
      commandOptions: [
        { command: "awk -F, '$3==\"RULE_CREATE\" && $4==\"svc-mailmigrate\" {print $1}' /var/log/mail/audit.csv | wc -l", correct: true, teaches: CORRECT_STEP },
        { command: "awk -F, '$3==\"Archived Mail\" {print $2, $6}' /evidence/mail/folder-stats.csv", correct: true, teaches: ALSO_WORKS },
        { command: 'systemctl status mail-platform', ...STATUS_CHECK },
        { command: 'cat /var/log/mail/audit.csv', ...DUMP_ALL },
        { command: 'grep -c RULE_CREATE /var/log/mail/audit.csv', ...COUNT_ONLY },
      ],
      commandNudge:
        'Check who created this rule and whether anybody ever opens the folder it writes to.',
      guidance:
        'It looks like the bad ones. Ask what was different about those.',
    },
  ],
};
